### ISSUE TITLE
Possible inconsistency in Python webhook code for inbound SMS

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#1000]
## Description

On this page:

https://developer.nexmo.com/messaging/sms/building-blocks/receiving-an-sms

The Python code snippet will work but is slightly inconsistent:

``` python
@app.route('/webhooks/inbound-sms', methods=['GET', 'POST'])
def delivery_receipt():
    if request.is_json:
        pprint(request.get_json())
    else:
        data = dict(request.form) or dict(request.args)
        pprint(data)

    return ('', 204)

app.run(port=3000)
```

Note the route is for inbound-sms and the block is for inbound SMS, but the function is named `delivery-receipt`.

There may be other blocks that have this inconsistency.

**Comment by arshadkazmi42** [comment]
I am taking this up

**Comment by mheap** [comment]
@arshadkazmi42 You may find the following links useful:

* https://developer.nexmo.com/contribute/structure/guides/building-blocks
* https://github.com/nexmo-community/nexmo-python-quickstart

**Comment by arshadkazmi42** [comment]
Created PR [nexmo-community/nexmo-python-quickstart](https://github.com/nexmo-community/nexmo-python-quickstart/pull/37)
