### ISSUE TITLE
API Ref endpoints have additional whitespace

### ISSUE THREAD

**Issue by sammachin** [Nexmo/nexmo-developer#1008]
## Description

On the API reference pages eg https://developer.nexmo.com/api/voice#getCall there is a space (%20) char between  the `v1` and  `/` where the coloring changes from base URL to endpoint specific.
This isn't obvious unless you try and copy/paste that string.
`https://api.nexmo.com/v1 /calls/:uuid `

This also appears to be the same on the SMS pages https://developer.nexmo.com/api/sms#send-an-sms between the `.com` and `/`
`https://rest.nexmo.com /sms/:format` 
 So could be to do with the way we are coloring the strings
## What did you expect to happen?

The URL to be correct eg
`https://api.nexmo.com/v1/calls/:uuid `

**Comment by lornajane** [comment]
I have seen this before and wondered if it was there to cause the string to break in a sane place when the URLs need to wrap. It does make sense that the URL should be copyable though.

**Comment by michizhou** [comment]
@sammachin @lornajane I could take up this issue if it's alright with you two.

**Comment by akshatnitd** [comment]
@mheap I am not being able to reproduce this issue. Is it browser specific?

**Comment by mheap** [comment]
It's not - it was resolved with the Volta release yesterday
