### ISSUE TITLE
SMS response format documentation is incorrect.

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-developer#1016]
## Description

The *documented* sample response format looks like this (json):

```json
{
  "to": "447700900000",
  "message-id": "0A0000000123ABCD1",
  "status": "0",
  "remaining-balance": "3.14159265",
  "message-price": "0.03330000",
  "network": "12345"
}
```

... but what _actually_ get's returned from the server looks like this (python syntax):

```python
{'message-count': '1',
 'messages': [{'message-id': '0B000000196AD9AC',
               'message-price': '0.03330000',
               'network': '23410',
               'remaining-balance': '18.15719450',
               'status': '0',
               'to': '447700900401'}]}
```

The documentation is ignoring that the top-level dict, containing `message-count` and `messages`, documenting it as if a single `messages` list item is all that is returned by the server.

## Related resources

https://developer.nexmo.com/api/sms#send-an-sms

**Comment by peterjgrainger** [comment]
Can I take this one? Let me know if there is anything special I need to know when changing.

**Comment by mheap** [comment]
Please do! There's nothing special you need to know. Be aware that we support both `json` and `xml` for this endpoint. Please make a request to the Nexmo API and validate the data structure returned when updating the documentation

**Comment by vipulgupta2048** [comment]
@peterjgrainger Are you still working on it? If not I can get it done in a few hours.

**Comment by vipulgupta2048** [comment]
Hey, @peterjgrainger That's quite okay. Documentation tasks usually require time and are really good first issues. Go forward with it. 
Regarding your question, one could find the information that you are looking for [here](https://github.com/Nexmo/nexmo-developer/tree/master/_documentation/messaging/sms) probably. That's a good place to start. Try making the call as stated in the documentation, and update the response.

**Comment by peterjgrainger** [comment]
Ah I found it.  It was in a different repo https://github.com/Nexmo/api-specification/blob/8a2997351518eec32224dc08ec9a367bb82a3952/definitions/sms.yml

**Comment by mheap** [comment]
This was resolved in the `api-specification` repo (we're working on making this less painful!). Thanks @peterjgrainger
