### ISSUE TITLE
Titles aren't clickable

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1028]
## Description

I can't "click" on the titles on the Volta version of NDP. The previous version did have this feature so you could click the title that you wanted to link someone directly to, and then copy its URL, e.g. https://developer.nexmo.com/concepts/guides/signing-messages#implementing-the-message-signing-workflow

## What did you expect to happen?

I'd be able to click on titles to get the correct internal link for this title.

## What actually happened?

The titles don't seem to be links

## Steps to reproduce:

Go to any long documentation page, and try to click on a title (bearing in mind my "click" will be with Vimium, I don't see labels on titles) so that you get the direct internal link to that heading in your address bar.

**Comment by mheap** [comment]
@BennyZ28 Mistakenly assigned myself to this one. Please could you take a look? The deep links are important (thanks for spotting @lornajane!)

**Comment by BennyZ28** [comment]
I might have removed them when I put in the icon titles but, if that's so then they'd just need to be brought back, they can definitely coexist! (Also sorry I typed this yesterday and forgot to hit send...)

**Comment by lornajane** [comment]
Did we reinstate the title links?

**Comment by mheap** [comment]
Ah this is my mistake. I misread it as tab links. Please reopen as linking to titles is a core part of NDP

**Comment by BennyZ28** [comment]
Fixed
