### ISSUE TITLE
Messages and Dispatch building blocks refer to creating voice app in 'create app' section

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#1045]
## Description

There are really two issues here. 

1) Support needs to be added to CLI for creating Messages and Dispatch apps
2) Building blocks should possibly be able to distinguish between app types. For example "stitch", "olympus", and "voice apps" (although possibly not using those names)

**Comment by tbedford** [comment]
@mheap FYI

**Comment by mheap** [comment]
I'll add support to NDP for application types. For now, you can use `use_existing` to add arbitary text:

```
application:
  use_existing: |
    Any text you put here will be put in to the building block
```
