### ISSUE TITLE
Clarify SMS API reference for `concat`

### ISSUE THREAD

**Issue by mheap** [Nexmo/nexmo-developer#1054]
## Description

SMS API reference isn't clear when the `concat` appears in the response. Can it appear and be `false`, or if it's not concatenated is it not set?

## Related resources

https://github.com/Nexmo/nexmo-php/issues/114

**Comment by vipulgupta2048** [comment]
@mheap Can I take this up?

**Comment by mheap** [comment]
https://github.com/Nexmo/nexmo-developer/pull/1184
