### ISSUE TITLE
Docker - webpack-dev-server support

### ISSUE THREAD

**Issue by adambutler** [Nexmo/nexmo-developer#107]
## Description

Currently `./bin/webpack-dev-server` is run outside of Docker. Support should be added for this to run as part of the `docker-compose up` task.

**Comment by plaindocs** [comment]
As a workaround, do you fancy pointing me in the direction of making it work outside of the docker container?

**Comment by adambutler** [comment]
Sorry, this should have been closed. When we changed to Webpacker 3 this step is no longer required.

**Comment by plaindocs** [comment]
When following the docker instructions two days ago I get a webpack related error though.

**Comment by adambutler** [comment]
This may still be unrelated if you are still getting an error feel free to open an issue providing more details on the exact error you are receiving.
