### ISSUE TITLE
nexmoOAuthDriver.sample

### ISSUE THREAD

**Issue by SoftCreatR** [Nexmo/nexmo-developer#1072]
On https://developer.nexmo.com/concepts/guides/oauth#running-the-sample-app it says:

`Download the sample from (file: nexmoOAuthDriver.sample text: nexmoOAuthDriver) and rename it nexmoOAuthDriver.php.`

Something is obviously missing, because the sample file doesn't exist, yet. However, imho i would just remove this instruction, because the example code is too unspecific. Alternatively, pick one specific OAuth 1 lib and create an example that works with it.

**Comment by mheap** [comment]
We've removed the oauth section as it's unused
