### ISSUE TITLE
New APIs don't have icons

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1078]
## Description

Last week we launched new products:

 - Messages API
 - Dispatch API

These appear in the new volta menu https://nexmo-developer-staging-pr-825.herokuapp.com/documentation without icons, which looks strange.

## What did you expect to happen?

All menu items would have an icon

## What actually happened?

The new menu items don't have icons

**Comment by thalaeg** [comment]
I will take care of this by the end of the day

**Comment by mheap** [comment]
Hey @thalaeg, thanks for offering but @BennyZ28 is working on this at the moment

**Comment by lornajane** [comment]
Looks good!
