### ISSUE TITLE
Some API docs pages don't render

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1097]
## Description

I notice that on the Volta branch, some API docs pages aren't rendering on the Preview app:

* https://nexmo-developer-staging-pr-825.herokuapp.com/api/number-insight
* https://nexmo-developer-staging-pr-825.herokuapp.com/api/sms

## What did you expect to happen?

API docs should appear

## What actually happened?

The error "We're sorry but something went wrong" is shown.

**Comment by mheap** [comment]
Resolved in 9b00e53380676f787b5824dad2e79d535abc136e
