### ISSUE TITLE
Consistency in using 'the' when referring to APIs

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#1109]
## Description

Need to check docs for consistency in use of 'the' when referring to APIs. 

For example, this page:

https://developer.nexmo.com/tutorials/sending-whatsapp-messages-with-messages-api

Does not use 'the' in the title.

**Comment by arshadkazmi42** [comment]
I can work on this. Starting with the page you have mentioned. 
Just for confirming, `the` needs to be removed from these types of statements too  `the Nexmo`. Am I right?

**Comment by mheap** [comment]
The opposite - the page linked page should say `messages with the Messages API`

**Comment by arshadkazmi42** [comment]
and the title which says `The steps`, does it needs to be changed to `Steps`? Or its just for the API

**Comment by arshadkazmi42** [comment]
Created a PR for this 👍

**Comment by mheap** [comment]
Merged in, thanks @arshadkazmi42
