### ISSUE TITLE
Update icons for stitch section on main page

### ISSUE THREAD

**Issue by AlexLakatos** [Nexmo/nexmo-developer#1111]
## Description

Update icons for stitch section on main page. Maybe re-use the old ones if we don't have new ones. The generic ones in there just make the whole section look "wip".

## What did you expect to happen?

Different icons for the Stitch Android, iOS and JS panels on main page.

**Comment by lornajane** [comment]
@BennyZ28 Do we have the stitch icons available? The main one is a microphone with a little message icon on it, then there are also three with a mobile phone plus a speech bubble, a microphone or a play button (for video).

**Comment by BennyZ28** [comment]
Fixed on volta-post
