### ISSUE TITLE
Podcast landing page style

### ISSUE THREAD

**Issue by mheap** [Nexmo/nexmo-developer#1115]
## Description

We have some unstyled content on https://developer.nexmo.com/hansel

#### The CTA button is no longer a button

<img width="106" alt="screen shot 2018-10-18 at 22 40 23" src="https://user-images.githubusercontent.com/59130/47151945-f8baa680-d326-11e8-810c-39fcc4f1fb78.png">
<img width="122" alt="screen shot 2018-10-18 at 22 40 28" src="https://user-images.githubusercontent.com/59130/47151946-f9533d00-d326-11e8-960d-21f3d1579e9a.png">

#### It's not obvious that you can click on Slack Community

<img width="458" alt="screen shot 2018-10-18 at 22 40 33" src="https://user-images.githubusercontent.com/59130/47152187-b80f5d00-d327-11e8-95c6-5f7f1b23269a.png">
<img width="534" alt="screen shot 2018-10-18 at 22 40 36" src="https://user-images.githubusercontent.com/59130/47152188-b80f5d00-d327-11e8-83d6-a28039ad90e5.png">

#### We've lost card-like styling on the blog posts

<img width="1290" alt="screen shot 2018-10-18 at 22 40 50" src="https://user-images.githubusercontent.com/59130/47152233-d4ab9500-d327-11e8-8520-4b90ca0f32cb.png">
<img width="1282" alt="screen shot 2018-10-18 at 22 40 55" src="https://user-images.githubusercontent.com/59130/47152240-db3a0c80-d327-11e8-8307-1ad96b8cfefa.png">

#### We've lost Github-like styling on the tools

<img width="1275" alt="screen shot 2018-10-18 at 22 41 02" src="https://user-images.githubusercontent.com/59130/47152297-06bcf700-d328-11e8-9728-30b2ebb7fd70.png">
<img width="294" alt="screen shot 2018-10-18 at 22 41 07" src="https://user-images.githubusercontent.com/59130/47152298-0886ba80-d328-11e8-81db-0dce2eabc75f.png">

**Comment by BennyZ28** [comment]
Fixed on volta-post
