### ISSUE TITLE
Additional Scroll Bar on Language Tab UL

### ISSUE THREAD

**Issue by cr0wst** [Nexmo/nexmo-developer#1123]
## Description

There appears to be a scroll bar on the right side of the languages tab list:

![image](https://user-images.githubusercontent.com/8314724/47187172-1bd25f80-d301-11e8-81a0-e6d4ad63b515.png)

https://developer.nexmo.com/dispatch/building-blocks/send-a-viber-message-with-failover/node

Not sure if Volta related.

**Comment by Rishabh570** [comment]
@cr0wst I would like to take this up. Can I work on it?

**Comment by mheap** [comment]
This doesn't show for me. @cr0wst can you share browser/resolution information?

**Comment by Rishabh570** [comment]
@mheap That little scroll bar is there...I would like to work on this, can you assign it to me?

![screenshot from 2018-10-19 09-09-37](https://user-images.githubusercontent.com/25483260/47196560-cd63a600-d37e-11e8-9f6f-31839fd5ebe2.png)

**Comment by mheap** [comment]
@Rishabh570 I'll have to defer to @BennyZ28 on this one, as she's our frontend expert

**Comment by Rishabh570** [comment]
@mheap Oh, okay! BTW I was able to resolve this just by doing `overflow: hidden`, hope it'll help :)

**Comment by lornajane** [comment]
It's there for me too on Chrome

**Comment by akshatnitd** [comment]
@cr0wst @BennyZ28 Can I work on this and can it be assigned to me?

**Comment by BennyZ28** [comment]
Lemme just have a look because we got a few other options for tabs in Volta
that might help

**Comment by cr0wst** [comment]
@BennyZ28 it looks like the tabs might be too tall to fit in the container. I'm using `Version 69.0.3497.100 (Official Build) (64-bit)` It also appears in Safari.

**Comment by akshatnitd** [comment]
@cr0wst I had checked the CSS. It seems that there is an extra `1 px` at the bottom the container due to which the scroll is taking place. Also, this happens when the `active` class is applied to the tab. Therefore the extra `1 px` is because of the active state of the tab. One possible solution is to hide the scroll by using `overflow: hidden`

**Comment by BennyZ28** [comment]
Ok this is a Volta issue, I'm fixing it in Volta and it'll be available
from the next update

**Comment by mheap** [comment]
This is on me to update volta in NDP

**Comment by brittBarak** [comment]
In addition to Chrome, it also appears on Windows, or IE & Edge. you might want to make sure the update fixes those as well.

**Comment by BennyZ28** [comment]
This was fixed in Volta, you guys just need to update it
