### ISSUE TITLE
Add note on port numbers

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#1145]
## Description

Svetlana Beliakova [5 days ago]
Hey team, I have noticed that in JS Stitch Quickstart guide we have this `Load localhost:8080 in two side-by-side browser windows.`. But I would suggest adding a tiny note there that port can be different to be more consistent, what do you think? We do not that path can be different above though. :slightly_smiling_face: Thank you!

Svetlana Beliakova [5 days ago]
https://developer.nexmo.com/stitch/in-app-messaging/guides/simple-conversation/javascript

Follow up to clarify the issue and apply the fix.

**Comment by dodococo** [comment]
Sounds like a good idea and I'd like to work on this issue.
