### ISSUE TITLE
Unability to signup with my social account.

### ISSUE THREAD

**Issue by dagolinuxoid** [Nexmo/nexmo-developer#1174]
## Description

You cannot signup with your social account, please create a Nexmo account

## What did you expect to happen?

Being successfully signed in.

## What actually happened?
I've got:
**You cannot signup with your social account, please create a Nexmo account** message

## Steps to reproduce
Go to [singup link](https://dashboard.nexmo.com/sign-in)
Click to GitHub/Google icon below **Or sign in** section (both don't work)

**Comment by mheap** [comment]
Hey @dagolinuxoid,

Could you email support@nexmo.com with this information? That team is better situated to help you sign up for an account
