### ISSUE TITLE
Some tabs show `<ol>` numbers

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1188]
## Description

On pages such as https://developer.nexmo.com/concepts/guides/applications/ where we have numbered bullets inside tabs, the numbers sometimes appear on some of the tabs.

## What did you expect to happen?

Numbers on bullet points, not on tabs.

## What actually happened?

See screenshot

![image](https://user-images.githubusercontent.com/172607/47778650-3c31ef00-dcef-11e8-89c9-7aaa617c5c3a.png)

**Comment by mheap** [comment]
```
ol.Vlt-list--simple {
	counter-reset: list;

	ol {
		counter-reset: list;
	}

	li {
		&:before {
			content: counter(list) '.';
			counter-increment: list;
			font-weight: 600;
			left: -20px;
			position: absolute;
			top: 0em;
		}
	}
}
```

The nested `li` needs a direct child selector `> li` rather than just an `li`, or any nested `ul`s will keep incrementing the counter.

I'm leaving this with @BennyZ28 to fix in Volta itself, and we'll pull an update in to NDP
