### ISSUE TITLE
Link to Messages API Reference Broken

### ISSUE THREAD

**Issue by sammachin** [Nexmo/nexmo-developer#1206]
The Link to `Messages API Reference` at the bottom of `https://developer.nexmo.com/messages/overview` points to `https://developer.nexmo.com/api/messages`

However if you click this link you are then redirected to `https://developer.nexmo.com/api/developer/account`

**Comment by lornajane** [comment]
There's more than one thing going on here. The API reference should be `/api/messages-olympus` so I'll fix that.

There's also a bunch of interesting redirects, I'm not sure why they are there:
```
"/api/developer": "/api/developer/account"
"/api/account": "/api/developer/account"
"/api/messages": "/api/developer/account"
"/api/numbers": "/api/developer/account"
```
So we should take a look at those before closing this issue.
