### ISSUE TITLE
Know how to write and write a webhook server?

### ISSUE THREAD

**Issue by carlos845** [Nexmo/nexmo-developer#1216]
## Description

Please briefly describe what the issue is

## What did you expect to happen?

Delete section if this is not a bug.

## What actually happened?

Delete section if this is not a bug.

## Steps to reproduce:

Delete section if this is not a bug.

## Related resources

Route links & Documents paths that might be helpful. Delete section if not appropriate.

**Comment by carlos845** [comment]
The hyperlink directing to` https://developer.nexmo.com/messages/building-blocks/inbound-message ` seems in error. Do you mean "read" and write?

**Comment by mheap** [comment]
Can you share which page you see this text on? I can't find it by searching

**Comment by tbedford** [comment]
Typo. Fix on the way. Thanks for spotting! :)
