### ISSUE TITLE
Query string authentication needs clarification

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#1220]
## Description

Issue raised from Slack...

---
Hi!, I’m trying to use this endpoint to get the numbers for a given account

https://developer.nexmo.com/api/developer/numbers

It says that I need to send api key and secret in query parameters
https://developer.nexmo.com/concepts/guides/authentication#query-string
but I don’t know which parameters are them, I’m trying with `https://rest.nexmo.com/account/numbers?apikey=....&secret=...`, but it does not work

---
it would be `api_key=`  and `api_secret=`

@tony.bedford I don’t think we specify this anywhere in our docs explicitly anymore.

I would include them here: https://developer.nexmo.com/concepts/guides/authentication#query-string

and here too `https://developer.nexmo.com/api/developer/account`

and probably somewhere else, but not everywhere :thinking_face:

Tony Bedford [< 1 minute ago]
I’ll capture this in a GitHub issue.

----

@lornajane : had a feeling you and Mark are currently looking this area? Feel free to assign back to me if not. Thanks.

**Comment by lornajane** [comment]
This was handled in #1276
