### ISSUE TITLE
Slow performance for Messages and Olympus API page

### ISSUE THREAD

**Issue by antonalechnovic** [Nexmo/nexmo-developer#1232]
## Description

The [messages-olympus api docs page](https://developer.nexmo.com/api/messages-olympus) performance is incredibly slow on Chrome(almost 70 % of browser market share). 

 ## What did you expect to happen?

During scroll I expect smooth flight like in Firefox and Safari.

## What actually happened?

Incredibly slow and jittery scroll. Impossible to navigate the page.

## Steps to reproduce:

Open page and scroll down

**Comment by mheap** [comment]
I've spoken to @antonalechnovic about this. I can't reproduce locally (same version of Chrome), and it seems to affect some people but not others.

@antonalechnovic is creating a video to show the effect
