### ISSUE TITLE
Overview Pages are moved in left hand menus

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1243]
## Description

We usually have "Overview" as the first entry in each product-specific menu in the left hand pane.  It looks like those pages have been renamed and so they now appear last on the list of navigation items for each product, e.g. https://developer.nexmo.com/verify/overview  The pages themselves are still there, the content is fine, I think just the nav is a bit weird.

## What did you expect to happen?

"Overview" as the first menu item

## What actually happened?

The menu link is called "2FA with Verify Nexmo API" instead and appears after all the other menu links for Verify.

## Steps to reproduce:

Go to https://developer.nexmo.com/verify/overview and look at the left hand menu. Other sections (e.g. Redact) are also affected)

**Comment by mheap** [comment]
This was resolved in 1ac7eda94cf394ad27c124ac5ab05f1a1ecc754e
