### ISSUE TITLE
Provide a way to get to the Application API Reference (and probably other non-product APIs) from the home page and docs page

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#129]
At present I can't quickly get to the Application API Reference page from the home page or the docs home page. I think it's an important API and it should be possible to get to it quickly:
https://developer.nexmo.com/api/application

**Comment by adambutler** [comment]
Aligns with #250 which I will make the canonical issue. Closing in favour of consolidating.
