### ISSUE TITLE
Lost images in reporting tutorial

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1292]
## Description

on the EA site, the images don't appear in the tutorial (branch `oas/reporting`) post. The assets exist, but I can't open them on my laptop.

## What did you expect to happen?

See a nice tutorial with images

## What actually happened?

No images

## Steps to reproduce:

Go to https://ea.developer.nexmo.com/reporting/tutorial and observe.

## Related resources

Look in `public/assets/images` for the images named `figure 1.png` (and 2, 3, 4)

**Comment by mheap** [comment]
Resolved in 4e92cd6c77d00d07f933eeda93d8ec9b268c8905 and deployed to EA
