### ISSUE TITLE
OpenAPI spec rendering should fall back to OperationID if Summary is not provided

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1300]
## Description

Summary is an optional field in OpenAPI, but our rendering relies on it and simply displays blank titles and navigation is not present.

## What did you expect to happen?

Some other operation-specific field would be used

## What actually happened?

Blank spaces

## Steps to reproduce:

Render an OpenAPI spec on NDP where the spec has an operation that does not have a summary field.

**Comment by mheap** [comment]
@lornajane Should we have a standard naming for operation IDs? `camelCase`? `kebab-case`? Bear in mind that these are also used as URL anchors

**Comment by mheap** [comment]
👍 Sounds good to me.

So for an `operationId` of `createSecret` it would show a title of `Create Secret`.

* `createSecret` => `Create Secret`
* `CreateSecret` => `Create Secret`
* `create-secret` => `Create-secret`
* `create_secret` => `Create_secret`

**Comment by mheap** [comment]
One for @benhayehudi

**Comment by benhayehudi** [comment]
I've opened a PR #1313 that works on addressing this issue. Looking forward to reviewing.

**Comment by benhayehudi** [comment]
I think this issue has been resolved with #1313. Is it okay to go ahead and close out this issue?
