### ISSUE TITLE
Use Tags when rendering OpenAPI reference docs

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1303]
## Description

In OpenAPI tags are used to group operations. We have something similar with the `x-group` functionality that groups the items together in the navigation. Tags is the standard OpenAPI way to do this, we should adopt it and use it in our rendering.

It might be nice to also use titles and descriptions as section starters, as ReDoc does.

The (not yet merged but I'm working on it) account API uses tags if you'd like an example.

**Comment by mheap** [comment]
One for @benhayehudi

`x-group` is the name of a group for the endpoint to be placed in (see `x-groups` at the bottom of an OAS doc). In addition to looking at `x-group`, we'd like Nexmo Developer to check if there's a `tags` section in the endpoint definition and put the endpoint in any groups defined in tags in addition.

This means that a single endpoint could show up in multiple groups in the sidebar

**Comment by mheap** [comment]
If an endpoint is associated with multiple tags, we can render it multiple times in the OAS for now so that the ordering is consistent

**Comment by benhayehudi** [comment]
I believe this issue has been resolved with the pull request #1308. Should we go ahead and close out this one?
