### ISSUE TITLE
Left hand side menu doesn't scroll after navigation

### ISSUE THREAD

**Issue by brittBarak** [Nexmo/nexmo-developer#1312]
## Description

When clicking on the left in order to navigate to some page --> the page opens up, but the left hand side menu scrolls to the top instead of to the link to page that opens.

## What did you expect to happen?

The left hand side menu to scroll to a position that shows the title of the page that is selected, in order to help the reader with orientation. 

## What actually happened?

The left hand side menu scrolls to the top.

## Steps to reproduce:

Go to NDP --> click on a link from the left had side menu that is relatively on the bottom of the page. (I'm using Chrome on Mac)

**Comment by benhayehudi** [comment]
I believe @cr0wst raised this same issue in #1119 opened on 18/10.

**Comment by mheap** [comment]
He did indeed! Closing this in favour of #1119
