### ISSUE TITLE
Add support for copy-to-clipboard for tutorials

### ISSUE THREAD

**Issue by brittBarak** [Nexmo/nexmo-developer#1387]
## Description

When writing a tutorial, and I have a code block bit, I'd like to add a "copy to clipboard" button to the code sample (similar as we have for building blocks). so that it's easier for the reader to copy the code sample and paste it to the reader's codebase.

**Comment by tbedford** [comment]
Assigned to Ben for an initial investigation on how possible this is to add to NDP.

**Comment by mheap** [comment]
Our existing copy to clipboard functionality is very specific to code snippets. We can make this work, but it'll take some refactoring
