### ISSUE TITLE
Code Snippet horizontal scroll bar appears on top bar

### ISSUE THREAD

**Issue by brittBarak** [Nexmo/nexmo-developer#1403]
## Description

In a tutorial page, when scrolling up, the horizontal scroll bar of the code snippet appears on the top bar

link to gif: https://drive.google.com/open?id=1wj_VTnJZy6OtPvTlVDgSkQvUFns0WqnK

## Steps to reproduce:

I  use Chrome on mac, that's the link for example: https://developer.nexmo.com/tutorials/client-sdk-ios-make-receive-calls-objective-c

## Related resources

Route links & Documents paths that might be helpful. Delete section if not appropriate.

**Comment by brittBarak** [comment]
![feb-03-2019 18-58-41](https://user-images.githubusercontent.com/6793023/52182498-763af180-2806-11e9-87e4-a1d59eb61e3a.gif)

**Comment by mheap** [comment]
Thanks for the gif - it really helps understand the issue.

I can't reproduce the issue - also Chrome on a Mac (Version 71.0.3578.98 (Official Build) (64-bit))

Can anyone else reproduce the issue?
