### ISSUE TITLE
Missing Name Anchors for Delivery Receipt and Inbound Message

### ISSUE THREAD

**Issue by o-rod-1** [Nexmo/nexmo-developer#147]
## Description

In the following page:
https://developer.nexmo.com/api/sms

There are 4 links to name anchors in the section Send an SMS. Delivery Receipt and Inbound Message do not work.

## What did you expect to happen?

Click either of the links and have the scroll position take me to that section in the page.

## What actually happened?

Nothing happened after clicking either.

## Steps to reproduce:

Go to https://developer.nexmo.com/api/sms and click either Delivery Receipt or Inbound Message links.

## Related resources

https://developer.nexmo.com/api/sms#delivery_receipt
https://developer.nexmo.com/api/sms#inbound

![2017-06-22 23_06_20-nexmo developer _ sms _ api reference](https://user-images.githubusercontent.com/10967425/27468589-761ac98e-579f-11e7-808f-4abe273e34b3.png)

**Comment by adambutler** [comment]
@o-rod-1 Thanks for the detailed bug report. Fixed.

**Comment by o-rod-1** [comment]
@adambutler, You're welcome ;)
