### ISSUE TITLE
Generated JavaScript Client SDK docs need some updates

### ISSUE THREAD

**Issue by garann** [Nexmo/nexmo-developer#1484]
## Description

Some of the generated documentation for the JS Client SDK could use an update to be more accurate and/or useful. 

[Application](https://developer.nexmo.com/sdk/stitch/javascript/Application.html):

- Is it possible to do `new Application(...)` from the client? Other resources suggest this must be done on the server.
- `call()` appears to return a Promise, not a Call object.

[Conversation](https://developer.nexmo.com/sdk/stitch/javascript/Conversation.html):

- Here again, it's not clear how you might use the constructor on the client. It doesn't seem accessible as a member of either the ConversationClient or the Application
- `invite()`says it can be passed either an `id` or `username`, but does not seem to accept either or both as strings or as object properties

[ConversationClient](https://developer.nexmo.com/sdk/stitch/javascript/ConversationClient.html)

- Probably worth mentioning the token in the `login()` method signature, as well as the table

[Member](https://developer.nexmo.com/sdk/stitch/javascript/Member.html)

- It's not clear which params are needed to call the constructor, or if it should be called

[Call](https://developer.nexmo.com/sdk/stitch/javascript/Call.html)

- Also appears this constructor is not meant for direct client use?

**Comment by mheap** [comment]
@garann Is this the correct place for this issue? Feels like it should be against the JS SDK repo to me

**Comment by garann** [comment]
I talked to @kapekost about it and we thought here would be a good place to keep track of it, acknowledging he may not be able to get to it right away.

**Comment by mheap** [comment]
Could it live as an issue against the JS SDK repo? As NDP is a consumer of those docs and there's nothing that we can really do about this issue, NDP feels like the wrong place to keep track.

Perhaps a DEVX ticket in Jira is a better place if we can't use the SDK repo?

**Comment by kapekost** [comment]
hey :) not sure we followed up with this one, I am picking up the comments, and arranging to take care of the fixes in the sdk, 
but let me know if you guys decided on another way we can get this type of input please

Thanks
