### ISSUE TITLE
"Modify Call" docs need newer content from docs.nexmo.com

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-developer#149]
## Description

The modify call API reference says the only supported action is "hangup". The truth is that other actions are supported like earmuff, unearmuff, mute, unmute and transfer. The old docs site has been updated to say this, but the changes obviously haven't made their way across.

https://docs.nexmo.com/voice/voice-api/api-reference#call_modify_single

vs.

https://developer.nexmo.com/api/voice#payload-3

**Comment by adambutler** [comment]
cc/ @leggetter

**Comment by adambutler** [comment]
I believe this to be fixed by #222
