### ISSUE TITLE
Broken link for Verify Guides

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1501]
## Description

On the landing page and on the documentation page, the link to "Guides" under "Verify" points to https://developer.nexmo.com/verify/guides/verify-a-user which does not exist. Also if you just go to https://developer.nexmo.com/verify/guides this redirects to https://developer.nexmo.com/verify/guides/verify-a-user as well. I'm not sure if we can point to a collection of guides or if this link should be to a "chosen" guide (Verify now has two guides)

## What did you expect to happen?

See a guide to Verify

## What actually happened?

404 page

## Steps to reproduce:

Click on "Guides" under "Verify"

**Comment by mheap** [comment]
We can't point to a collection of guides at the moment, so let's point to `/verify/guides` on the landing + documentation pages and make that a redirect to `/verify/guides/verification-events`
