### ISSUE TITLE
Long code formatted text goes out of bounds

### ISSUE THREAD

**Issue by brittBarak** [Nexmo/nexmo-developer#1517]
## Description

Long text formatted as code goes out of bounds of the text area.

This is an example from:
https://developer.nexmo.com/tutorials/client-sdk-ios-inbound-pstn

<img width="1088" alt="Screen Shot 2019-03-10 at 13 00 13" src="https://user-images.githubusercontent.com/6793023/54086097-b3326080-433d-11e9-84ad-341aec59db95.png">

**Comment by mheap** [comment]
I checked with the Volta team and the way to handle long strings like this it to use a code fence (wrap it in \```) which will make it horizontally scrollable.
