### ISSUE TITLE
Try it out for SMS

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#1527]
## Description

Hi team, it seems that the *Try it out* feature is outdated here https://developer.nexmo.com/messaging/sms/guides/concatenation-and-encoding. It's due to we changed from 16 bits to 8 bits the UDH header as per https://nexmoinc.atlassian.net/browse/SMS-800.

Meaning that 134 characters are still two messages rather than 3. I've been trying to submit a PR but when I go to the location of `source: app/views/tools/concatenation.html` I can only see `<div id="ConcatenationComponent" class="Vlt-box"></div>`.

Can anyone help?

**Comment by lornajane** [comment]
I'm not clear what's broken here, are we splitting the messages at the wrong point?
