### ISSUE TITLE
SNS docs are outdated

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1546]
## Description

The SNS docs are outdated - we know that sns.nexmo.com no longer exists for example, and we're not sure if this product is still in use or how the docs should be updated.

## What did you expect to happen?

Accurate docs, or no docs.

## What actually happened?

Inaccurate docs

## Steps to reproduce:

Go to https://developer.nexmo.com/messaging/sns/overview

**Comment by pardel** [comment]
@elena.benedetti is part of the team that does pentesting on NDP and was asking if it's still a service we offer. 
If removed, they won't include the service in their work.

**Comment by mheap** [comment]
Docs removed
