### ISSUE TITLE
Link to a page and have a specific language shown in the code examples and related text

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#155]
## Description

It should be possible to link to a page and have a specific language shown in the code examples and related text e.g.

* cURL - https://developer.nexmo.com/messaging/sms/building-blocks/receiving-an-sms
* PHP -  https://developer.nexmo.com/messaging/sms/building-blocks/receiving-an-sms/php
* Node.JS - https://developer.nexmo.com/messaging/sms/building-blocks/receiving-an-sms/nodejs
* Java - https://developer.nexmo.com/messaging/sms/building-blocks/receiving-an-sms/java
* C# - https://developer.nexmo.com/messaging/sms/building-blocks/receiving-an-sms/c-sharp
* Python - https://developer.nexmo.com/messaging/sms/building-blocks/receiving-an-sms/python

Pages should also be discoverable and appear language specific (unique) to search engines.

**Comment by adambutler** [comment]
FYI: https://support.google.com/webmasters/answer/6080548?hl=en

**Comment by leggetter** [comment]
For consideration paths vs. parameters https://moz.com/blog/15-seo-best-practices-for-structuring-urls
