### ISSUE TITLE
API Docs missing JSON types

### ISSUE THREAD

**Issue by jlory** [Nexmo/nexmo-developer#1605]
First time using Nexmo API for receiving SMS and I noticed browsing the doc that JSON types are missing, I don't know if a field is a string an int a bool ect ...

Would be nice to have types for every fields, some of us use strongly typed languages and marshalling / unmarshalling is easier if you know the type beforehand.

**Comment by mheap** [comment]
Thanks for the suggestion! We have this data available [in our API specifications](https://github.com/Nexmo/api-specification/blob/master/definitions/sms.yml#L314) but it's not currently rendered. I've added an issue to show it on the rendered site too
