### ISSUE TITLE
"Update application" shows RTC capability as having answer callback/webhook 

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#1612]
## Description

In the page:

https://developer.nexmo.com/api/application.v2#updateApplication

For "update application" response it shows RTC capability as having both answer callback URL and event callback URL - I believe it should only be event callback URL. 

Also, if you try to set an answer callback for RTC capability you will get an error saying RTC capability can only have event callback set.

**Comment by tbedford** [comment]
@mheap : assigning to you for verification of issue.

**Comment by mheap** [comment]
Yep, this is correct. It should only have an `event_url`. Applications v1 accepts both but only uses event
