### ISSUE TITLE
check verification code 

### ISSUE THREAD

**Issue by spland** [Nexmo/nexmo-developer#1697]
This document does not have Java https://developer.nexmo.com/verify/code-snippets/check-verify-request
can anyone help me how to find it?

**Comment by lornajane** [comment]
I had a look in the Java library readme and found this https://github.com/Nexmo/nexmo-java#check-the-2fa-code - does that help?

**Comment by spland** [comment]
> I had a look in the Java library readme and found this https://github.com/Nexmo/nexmo-java#check-the-2fa-code - does that help?

oh ,i see it ,thanks
client.getVerifyClient().check(ongoingVerify.getRequestId(), CODE)
