### ISSUE TITLE
Replying to sms within response

### ISSUE THREAD

**Issue by sflowerlisa22** [Nexmo/nexmo-developer#1711]
I have recently switched over from Twilio and am not sure if I will have to re-write my code.

Twillio allows you to reply to a recieved sms within the response such as:

```
      res.writeHead(200, {'Content-Type': 'text/xml'});
      res.end(`
      <Response>
        <Message>
          This is the response
        </Message>
      </Response>
      `);
```

Is this possible with Nexmo

**Comment by mheap** [comment]
Hey Lisa,

Unfortunately you can't respond to an inbound SMS webhook with a response. You can however, use our node client library to send an SMS. See https://developer.nexmo.com/messaging/sms/code-snippets/send-an-sms/node for more information

Let us know if you need anything else!
