### ISSUE TITLE
API Reference parameters not visible on Windows in Chrome & Opera

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#1712]
## Description

The `api_key` parameter and other parameters are not rendered/visible.

![api_key-missing](https://user-images.githubusercontent.com/328367/58200010-a8933080-7cc9-11e9-8c98-68967c3b2c35.jpg)

On Chrome on Mac the parameters do seem to be rendred/visible.

Report from @alexbaban.

> I'm not sure what is, I'm on Windows with Chrome Version 74.0.3729.157 , I'm attaching another screenshot. If I went to override with 'font-weight: normal;' I could then see it.

![api_key-missing-2](https://user-images.githubusercontent.com/328367/58200122-ebed9f00-7cc9-11e9-9393-3cf4cf2963c4.png)

## What did you expect to happen?

Parameters should be visible.

**Comment by alexbaban** [comment]
Also the top horizontal menu and text on "Try it now" blue button next to "Sign in" are not visible.

**Comment by mheap** [comment]
@BennyZ28 Could this be a Volta issue?

**Comment by BennyZ28** [comment]
I don't have a windows machine I could try this on. Could someone with a windows machine check the main volta website, specifically the tabs section http://volta.vonage.com/tabs.html, and see if they work?

**Comment by alexbaban** [comment]
A BrowserStack [](https://www.browserstack.com/) account would come in handy.

**Comment by mheap** [comment]
I've found a windows machine to test on. Chrome `Version 74.0.3729.169 (Official Build) (64-bit)` and both the API reference and `Try it now` text are rendering correctly.

@BennyZ28 Sounds like this will need some investigation by the Volta team

**Comment by BennyZ28** [comment]
Ok, thanks for checking, I filed it in our jira
