### ISSUE TITLE
A location for legacy technical content?

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#172]
## Description

Although we will no longer be highlighting functionality such as the legacy Voice API or the Verify SDK the documentation should still be available online.

* https://docs.nexmo.com/voice/voice-deprecated
* https://docs.nexmo.com/verify/verify-sdk-for-android
* https://docs.nexmo.com/verify/verify-sdk-for-iOS
* https://docs.nexmo.com/verify/verify-sdk-for-javascript
* https://docs.nexmo.com/number-insight/ni_legacy

What are the plans for these?

**Comment by adambutler** [comment]
@leggetter I was planning on requesting `301 Moved Permanently` redirects for all URLs that have equivalent pages in Nexmo Developer.

You can see a list of redirects [here](https://docs.google.com/a/vonage.com/spreadsheets/d/1y3U40cdL7gh_6R-uJKmEs6LrXJGCBsD_J-jD2wcTJ3U/edit?usp=sharing).

**Comment by adambutler** [comment]
https://nexmoinc.atlassian.net/browse/OPS-5624

**Comment by adambutler** [comment]
@leggetter made a good point in that 301's will [be cached](https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s) preventing us from improving any redirects as we go forward and fixing any issues with the redirect configuration.

I'd, therefore, suggest that these should be 302 redirects and perhaps later promoted to 301 redirects once we have sufficient traffic to be confident with the rule set.

**Comment by adambutler** [comment]
@JonathanFarrow117 ☝️
