### ISSUE TITLE
Non-default HTTP method in Incoming SMS Building Blocks

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-developer#173]
The sample code for Node.js and Ruby in the Receiving an SMS [Building Block](https://developer.nexmo.com/messaging/sms/building-blocks/receiving-an-sms) set up GET endpoints to receive the incoming webhook.

By default, Nexmo accounts are set up to send the SMS webhooks with POST requests, not GET requests, so some configuration is required for these building blocks to work.

We should either change the sample code to accept POST requests (and probably also GET requests - I think the test requests made when a number is linked to the endpoint are GET requests regardless), or we should provide a link to docs instructing them to change their HTTP Method to GET in Dashboard Settings.

**Comment by leggetter** [comment]
> By default, Nexmo accounts are set up to send the SMS webhooks with POST requests, not GET requests, so some configuration is required for these building blocks to work.

@judy2k - this must have changed. I'm reasonably sure used to default to a `GET`. Can we check this change with @oschlieb?

Ideally, we should go with `POST` which makes a lot more sense for handling inbound SMS webhooks.

**Comment by adambutler** [comment]
@oschlieb Can you confirm the default method?

**Comment by oschlieb** [comment]
GET is default.

**Comment by tommorris** [comment]
As the default is `GET`, and both Ruby and Node.js code samples are `GET`-based, I don't think we need to change anything.

**Comment by AlexLakatos** [comment]
Can we make a note of this somewhere on the page? Ran into this issue today, and barely remembered I changed my account to POST a while back.
