### ISSUE TITLE
OpenAPI Specs with `oneOf` responses render response fields twice

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1743]
## Description

If you look at an API spec that uses `oneOf` to represent multiple possible response types (such as Verify API https://developer.nexmo.com/api/verify#verifyRequest), and view the response field descriptions, you get all the fields from all of the responses in a single list.

I'm not sure what the right thing to do here is, but I found this confusing.

Also Brennan mentioned that he thought the tabs on the right hand bar (again, specific to the `oneOf` rendering that has multiple possible responses) looked strange - can you take a look while you're looking at this endpoint anyway? Thanks!

**Comment by lornajane** [comment]
@fabianrbz is this something you can take a look at? I'm seeing it on the rendered OAS specs on the api-specifications repo as well, and it's particularly noticeable on the Verify API, which we're doing quite a lot of work on at the moment.

**Comment by fabianrbz** [comment]
@lornajane i'll take a look!

**Comment by lornajane** [comment]
This is looking much better now with the multiple responses in tabs. Thanks!
