### ISSUE TITLE
Searching from API reference page produces error

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1817]
## Description

From an API reference page (such as https://developer.nexmo.com/api/voice), type into the search box (this part seems fine) and submit the search query by pressing enter.

## What did you expect to happen?

See a list of search results as I would if I did this on any other page

## What actually happened?

I get an error about the change being rejected (see screenshot)
![Screenshot from 2019-07-05 09-06-36](https://user-images.githubusercontent.com/172607/60707714-42bed900-9f04-11e9-9433-2ad963e7a049.png)

**Comment by fabianrbz** [comment]
Fixed as part of https://github.com/Nexmo/nexmo-developer/pull/2232
