### ISSUE TITLE
Extra space in $action value causes curl request to fail.

### ISSUE THREAD

**Issue by o-rod-1** [Nexmo/nexmo-developer#183]
## Description

The code snippets at the following links have an extra space in the $action value that causes the curl request to fail.

https://developer.nexmo.com/api/application#retrieve-an-application
https://developer.nexmo.com/api/application#update-an-application
https://developer.nexmo.com/api/application#destroy-an-application

`$action = '/applications '; `
should be changed to
`$action = '/applications';`

![image](https://user-images.githubusercontent.com/10967425/27980066-d1dce09a-632f-11e7-81cd-de123f81a86a.png)

**Comment by adambutler** [comment]
Fixed by e01f470
