### ISSUE TITLE
Call status value should not be in a popup dialog and it should be possible to link to the table

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#191]
## Description

This is a similar case to that of #180. Can we please move so that `status` values are visible within the page in their own table and so that you can link directly to that table?

<img width="893" alt="screen shot 2017-07-11 at 14 05 52" src="https://user-images.githubusercontent.com/328367/28069668-2d937394-6642-11e7-8532-f01656be11a4.png">

**Comment by tommorris** [comment]
Will take a look at this today.
