### ISSUE TITLE
Tabbed content 404s when accessed directly

### ISSUE THREAD

**Issue by lukeocodes** [Nexmo/nexmo-developer#1945]
## Description

A user has found that tabbed content (specifically https://github.com/Nexmo/nexmo-developer/blob/master/_api/verify/templates.md) links 404 when accessed directly e.g. https://developer.nexmo.com/api/verify/templates/ruby 

But when we access the default page https://developer.nexmo.com/api/verify/templates it rewrites the URL to the one that 404s, despite the content being available. 

This is very confusing for the user. 

## What did you expect to happen?

https://developer.nexmo.com/api/verify/templates/ruby URL should work defaulting the examples to ruby where necessary

## What actually happened?

https://developer.nexmo.com/api/verify/templates/ruby URL 404s

## Steps to reproduce:

Open 
https://developer.nexmo.com/api/verify/templates/ruby directly

**Comment by fabianrbz** [comment]
Related https://github.com/Nexmo/nexmo-oas-renderer/pull/20
