### ISSUE TITLE
Inaccessible tabs

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#2015]
## Description

I'm no longer able to read the documentation on the NCCO Guide page. There are some tabs for "Single Option", "Single Value" and so on, but these seem to be some sort of special span tag, they aren't focusable or interactive.

The same applies to the language tabs (but only on this page, the code snippets work well in general for me at this point).

## What did you expect to happen?

I expected to be able to interact with the user interface

## What actually happened?

Nothing. I can see the tabs, but they're just display, they're not buttons or links or anything else I can focus.

## Steps to reproduce:

Go to https://developer.nexmo.com/voice/voice-api/guides/ncco and try using something that isn't a pointing device to access the tabs.

Please always let me know if you would like me to look at the tabs in any NDP changes, I'm always happy to! Right now, tabs in a couple of places and not being able to scroll the nav bar at all are reasons that I can't use some parts of the documentation and this might exclude our customers as well as our colleagues.

**Comment by brkn** [comment]
I would like to work on this.
