### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#206]
## Description

Although the release process is [documented](https://github.com/Nexmo/nexmo-java/wiki/Releasing-nexmo-java) it requires a manual process that can result in error.

Can we automate the following steps to ensure none are missed? Or at least perform checks to ensure if any are missed that they can be quickly rectified.

1. Updating the in-source CHANGELOG
2. Updating any version references in code (including build files)
3. Updating any version references in docs e.g. README
4. Releasing on GitHub
5. Publishing to Maven

**Comment by adambutler** [comment]
@leggetter I'm assuming this issue was opened on the wrong repo?

**Comment by leggetter** [comment]
@adambutler I was actually looking to see where I put this 🤦‍♂️
