### ISSUE TITLE
Search should index developer content on the nexmo blog

### ISSUE THREAD

**Issue by sammachin** [Nexmo/nexmo-developer#220]
There is a lot of useful technical content on the blog, things like x with y guides etc. It would be great if this was surfaced in search results, probably as a separate category much like the knowledge base.
This will help make Nexmo Developer the single start point for developers finding all things nexmo.

**Comment by lornajane** [comment]
This would be excellent, re-opening.

**Comment by mheap** [comment]
Closing as we'll move XwY in to NDP directly
