### ISSUE TITLE
Feature Request: API call to download pre-recorded phone calls as mp3

### ISSUE THREAD

**Issue by deanhouseholder** [Nexmo/nexmo-developer#224]
My Client has turned on the Vonage Business feature to auto-record all phone conversations.  He wants me to write a script to download these recordings and save them into Clio as a Document attached to a Matter.

I don't see any way to download these via an API call. Please let me know if I'm missing it.  The web interface seems to be the only way to do it.

**Comment by leggetter** [comment]
@deanhouseholder - You can't presently download your Vonage calls via the Nexmo Voice API. But I've passed this request on to the Product team.
