### ISSUE TITLE
tts

### ISSUE THREAD

**Issue by viennp8bit** [Nexmo/nexmo-developer#227]
## Description

Please briefly describe what the issue is

## What did you expect to happen?

Delete section if this is not a bug.

## What actually happened?

Delete section if this is not a bug.

## Steps to reproduce:

Delete section if this is not a bug.

## Related resources

Route links & Documents paths that might be helpful. Delete section if not appropriate.

**Comment by adambutler** [comment]
@viennp8bit I am not able to understand this issue as it does not provide a description.

For now, I will close this issue. If you would like it reopened please edit your issue description providing information as outlined by the template.

**Comment by viennp8bit** [comment]
@adambutler 
Sorry, I just searched with keyword "tts" and leaved this page, but I didn't know GitHub created a new issue for you. 
Please ignore it, thank you.
