### ISSUE TITLE
Rubycritic

### ISSUE THREAD

**Issue by mheap** [Nexmo/nexmo-developer#2312]
Would https://github.com/whitesmith/rubycritic be a useful addition to the project?

**Comment by fabianrbz** [comment]
Yes, I'm not very familiar with that one in particular but it definitely helps. We could use https://codeclimate.com/ as well, which is free for OSS projects

**Comment by benhayehudi** [comment]
I would be happy with either. I will say that I appreciate the responsiveness of the project to issues raised in the repo, and addressing them. You can see the recent v4.3.1 release in response to an issue raised as an example of that.
