### ISSUE TITLE
Account creation step is wrong

### ISSUE THREAD

**Issue by krisbailey** [Nexmo/nexmo-developer#2457]
## Description

I click the link to sign into "Vonage UC extended".

## What did you expect to happen?

I expected to be able to sign in at the page linked to

## What actually happened?

I was unable to sign in with my valid credentials.  I've also gone through the "request access" process noted on the page at least 10 times, and emailed their support as well -- no response from anyone and still can't sign in.

## Steps to reproduce:

Click the "Vonage UC extended" link in step 1.
Try to sign in with a regular Vonage Business Cloud account that you haven't had specially prepared.
Watch it fail.

## Related resources

https://developer.vonage.com/store/

**Comment by fabianrbz** [comment]
@krisbailey still having issues? if so, we can redo the credentials.

**Comment by krisbailey** [comment]
Where did you send it?  I just looked at my email and I don't see
anything.  Can you forward me the email chain?

**Comment by fabianrbz** [comment]
Closing this, we continue over email.
