### ISSUE TITLE
Difficult to find Message Search API reference from homepage

### ISSUE THREAD

**Issue by tommorris** [Nexmo/nexmo-developer#250]
## Description

It is quite difficult to locate the Message Search API from the homepage. It's tucked away on `/api` but not available from the homepage. If you click on the API reference link for Account on the homepage, you are taken to `/api/developer/account`. The current shortest way to find the Message Search API is

* Homepage → API Reference (menubar) → Messages

This is a bit misleading.

This is similar to the issue in #218 in that the Voice API reference is accessible from the home page but the NCCO reference is not.

## Related resources

* [Slack thread](https://nexmo.slack.com/archives/C04HCA4BF/p1501173806392291) (internal-only)

**Comment by adambutler** [comment]
Similar issue #129 raised by @leggetter 

> At present I can't quickly get to the Application API Reference page from the home page or the docs home page. I think it's an important API and it should be possible to get to it quickly:
https://developer.nexmo.com/api/application
