### ISSUE TITLE
SMS Delivery error codes are not documented in NDP

### ISSUE THREAD

**Issue by HelenFoot** [Nexmo/nexmo-developer#269]
## Description

Delivery receipt errors for SMS have different meanings to the API response codes and only the API response codes are documented in NDP, not the delivery receipt error codes

## What did you expect to happen?

I expected delivery receipt errors to have a similar table to the response codes errors

## What actually happened?

It doesn't exist

## Steps to reproduce:

Go to https://developer.nexmo.com/api/sms
Scroll down to delivery receipts
No documentation on their error codes exists

## Related resources

https://help.nexmo.com/hc/en-us/articles/204014733 is the content that should be there
https://developer.nexmo.com/api/sms#error-codes is the content for response codes
https://help.nexmo.com/hc/en-us/articles/204827547-Why-are-there-different-meanings-to-Nexmo-SMS-Error-Codes-

**Comment by adambutler** [comment]
Delivery receipt errors are present within this page under [Delivery Receipt > Keys and Values](https://developer.nexmo.com/api/sms#keys-and-values-2)

This section contains a table of keys and values. One of the keys is `err-code` and these error codes and their descriptions can be seen by clicking the possible values button.

See GIF-cast for details:

![2017-08-09 16 35 09](https://user-images.githubusercontent.com/1238468/29130121-d2693e54-7d20-11e7-9452-4c9928907232.gif)

I'll close this issue for now, feel free to reopen if you think I have misunderstood.

**Comment by HelenFoot** [comment]
Thanks, no, you haven't misunderstood. I missed that they were included
there.

Can I just ask why this is not presented in a table that is a subheading
and linkable to in the same way the response code error codes are? Is this
text searchable?

Kind regards,
Helen Foot
Support Operations Manager


NEXMO, the Vonage API Platform | 1st floor, 44 Featherstone Street | London
 EC1Y 8RN |  UNITED KINGDOM
helen.foot@vonage.com | Skype: helen.nexmo
