### ISSUE TITLE
Broken links at https://help.nexmo.com/hc/en-us/articles/204014803-Getting-started-sending-SMS-guide

### ISSUE THREAD

**Issue by jshub-nexmo** [Nexmo/nexmo-developer#280]
## Description

When clicking on any of the links under "Next Steps" section at the bottom of https://help.nexmo.com/hc/en-us/articles/204014803-Getting-started-sending-SMS-guide page you are redirected to https://developer.nexmo.com/

## What did you expect to happen?
Redirected to the respective subject page.
For example, for OAuth - need to be redirected to https://developer.nexmo.com/concepts/guides/oauth.

## What actually happened?

Redirected to https://developer.nexmo.com/

## Steps to reproduce:

1. Go to //help.nexmo.com/hc/en-us/articles/204014803-Getting-started-sending-SMS-guide
2. Scroll to "Next Steps" at the bottom and click "OAuth" (for example)

## Related resources

Route links & Documents paths that might be helpful. Delete section if not appropriate.

**Comment by peter-nexmo** [comment]
The Knowledgebase article has now been updated.

**Comment by tommorris** [comment]
Thanks @peter-nexmo and @jshub-nexmo.
