### ISSUE TITLE
NEXMO_BRAND_NAME is mentioned but not used

### ISSUE THREAD

**Issue by alexforrow** [Nexmo/nexmo-developer#2834]
## Description

In the 'Send an SMS' and 'Send an SMS with Unicode' code snippets, `NEXMO_BRAND_NAME` is included in the variable list but never used.

## What did you expect to happen?

Either `NEXMO_BRAND_NAME` should be removed from the variable list to avoid confusion, or it should be used in the code examples (though possibly with a different name, to align with `TO_NUMBER`)

**Comment by tbedford** [comment]
Thanks Alex!

**Comment by alexforrow** [comment]
Thanks Tony :+1:

**Comment by tbedford** [comment]
I fixed the Curl and Python code snippets. @dragonmantank to fix PHP code snippet. @benhayehudi to fix Ruby code snippet. Thanks.

**Comment by fabianrbz** [comment]
@tbedford @dragonmantank @bencgreenberg has this been fixed?

**Comment by bencgreenberg** [comment]
No, looks like the cURL snippet needs to get edited for `VONAGE_BRAND_NAME` and the Ruby one needs to be updated to use the variable generally.

**Comment by bencgreenberg** [comment]
I'll submit a PR for the Ruby one.
