### ISSUE TITLE
Endpoint Array in connect NCCO not clearly marked

### ISSUE THREAD

**Issue by slorello89** [Nexmo/nexmo-developer#2849]
## Description

The endpoint field in the Connect NCCO Says "Connect to a single endpoint. Available endpoint types" - which implies that it's looking for one object. In reality the expected format is an array of objects. The description should be something a bit clearer - even though it does in fact only accept one object in the array

## Related resources

https://developer.nexmo.com/voice/voice-api/ncco-reference#connect

**Comment by benhayehudi** [comment]
Hi there @slorello89,

I don't think a change is necessary for this specific doc. The code example preceding it shows the format it is expecting as an array of objects. The text description in the table is also accurate that it is describing what it does, in that it connects to an endpoint.

**Comment by slorello89** [comment]
I disagree - the wording is very confusing - I know the first time I read it I thought it was referring to a single endpoint object as that's how I originally coded it. I'd say it should read like:

Array of `endpoint` objects to connect to. See [available endpoint types](https://developer.nexmo.com/voice/voice-api/ncco-reference#endpoint-types-and-values)
> Note: Supports a maximum of 1 endpoint object.

**Comment by benhayehudi** [comment]
> I disagree - the wording is very confusing - I know the first time I read it I thought it was referring to a single endpoint object as that's how I originally coded it. I'd say it should read like:

If it's confusing for you then it's going to be confusing to others as well. That's a good enough reason to modify it. I'll raise a pull request this morning with a change as you suggest here. Thanks for raising it, Steve!

> Array of `endpoint` objects to connect to. See [available endpoint types](https://developer.nexmo.com/voice/voice-api/ncco-reference#endpoint-types-and-values)
> 
> > Note: Supports a maximum of 1 endpoint object.

**Comment by benhayehudi** [comment]
Addressing this in #2853
