### ISSUE TITLE
ASP.NET delivery receipt building block code is cut short

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#292]
## Description

It doesn't show the receiving code. Just the debug outlines. Is the start-line incorrect?

<img width="978" alt="screen shot 2017-08-21 at 20 56 18" src="https://user-images.githubusercontent.com/328367/29533674-30956890-86b3-11e7-8dc5-fe19bd34efe4.png">

**Comment by tommorris** [comment]
I've also filed [PR 13](https://github.com/nexmo-community/nexmo-dotnet-quickstart/pull/13) with the nexmo-community/nexmo-dotnet-quickstarts to shorten the dashes from 73 to 36 characters so they don't overflow the window. Once that's been approved, I'll pull it in to NDP in a separate PR.
