### ISSUE TITLE
New strange scrolling/left-hand side menu behaviour

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#321]
## Description

Scrolling can:

1. Jump down upon scrolling down from the top
2. Jump up and down when scrolling from the bottom
3. Scroll so that now main content is seen
4. End up with the menu disappearing

![scrolling-fun](https://user-images.githubusercontent.com/328367/30030858-f9bda876-9186-11e7-8d32-1a35ed4741f7.gif)

Navigating can:

1. Have the menu appear over the header area

![screen shot 2017-09-04 at 15 36 27](https://user-images.githubusercontent.com/328367/30030866-ffd28542-9186-11e7-8a3b-8d6609e3655e.png)

**Comment by adambutler** [comment]
Not seeing this issue on:

Chrome 60.0.3112.113 on macOS Sierra
Chrome 60.0.3112.113 on Windows 10

To help debug:

1. Can you send me the link generated when you go to http://www.whatsmybrowser.org/
2. Can you check to see if there is any JS exceptions raised.
3. Can you clear your cache to ensure there aren't any old files being loaded in.

**Comment by leggetter** [comment]
1. whatsmybrowser.org/b/8AE2UC2
2. No JS errors raised. The fact the page often jumps or the menu disappears/reappears suggest that there's a flaw in scroll calculation logic.
3. That, unfortunately, doesn't make any difference
