### ISSUE TITLE
Improve/expand guide to Custom Objects in the Messages API

### ISSUE THREAD

**Issue by marklewin** [Nexmo/nexmo-developer#3222]
Hacktoberfest Documentation Task

## Description

Improve our guide to using Custom Objects in our Messages API? https://developer.nexmo.com/messages/concepts/custom-objects

Make it easier to understand and see the benefits of this approach. For extra credit, consider writing a "real life" use case.

**Comment by chilupa** [comment]
Hey @marklewin, I would like to contribute to this task. Could you please assign it to me?

**Comment by 3scava1i3r** [comment]
@marklewin what should we add , could you please provide us with some reference?
