### ISSUE TITLE
Create IVR menu tutorial using Node.js

### ISSUE THREAD

**Issue by marklewin** [Nexmo/nexmo-developer#3223]
Hacktoberfest Documentation Task

## Description

Our Interactive Voice Response example (https://developer.nexmo.com/use-cases/interactive-voice-response) shows you how to create a phone menu using PHP. Create another version of the tutorial using Node.js.

**Comment by spiritbro1** [comment]
hello could you elaborate more on where the tutorial should be submitted?

**Comment by marklewin** [comment]
Hello!

You need to raise a PR on this repository:
https://github.com/nexmo/nexmo-developer/

Details of how our tutorials are structured are available in the Contribution
Guide <https://developer.nexmo.com/contribute/overview>. Let me know if you
have any questions!

Best regards

Mark Lewin
Technical Writer, Vonage

**Comment by spiritbro1** [comment]
@marklewin thank you for the explanation, but i still confused to where to put my markdown tutorial after im done with it which folder in the https://github.com/nexmo/nexmo-developer/ should i put it in?

**Comment by marklewin** [comment]
@spiritbro1 Call it `ivr-node` and see [here](https://developer.nexmo.com/contribute/guides/tutorials#directory-structure) for placement.

**Comment by spiritbro1** [comment]
@marklewin so i should put it in _tutorial/en and also i should add a config file in config/en right?

**Comment by marklewin** [comment]
@spiritbro Correct! Ping me if you get stuck.
