### ISSUE TITLE
Convert SMS API blog posts to tutorials

### ISSUE THREAD

**Issue by marklewin** [Nexmo/nexmo-developer#3225]
Hacktoberfest Documentation Task

## Description

Many of our SMS API (https://developer.nexmo.com/messaging/sms/overview) tutorials currently link to blog posts. Can you convert one of more of these into our standard tutorial format (https://developer.nexmo.com/contribute/structure/guides/tutorials)?

Many of these blog posts are old and refer to old versions of the packages, frameworks, etc that they use. Please ensure versions, etc are up to date and work correctly. Also please consider that, because they are going onto our documentation site, they should use more formal plain English than they might be written in on the blog.

**Comment by mee-kell** [comment]
Hello! I took a crack at this with one blog post, and am planning to convert a couple more posts. Just wanted to PR the first post to make sure that the markdown and configuration are all up to standard. 😃

**Comment by niati** [comment]
@mee-kell [PR 3234](https://github.com/Nexmo/nexmo-developer/pull/3234) has been approved and merged.
