### ISSUE TITLE
Accessibility - broken alt text on images

### ISSUE THREAD

**Issue by edent** [Nexmo/nexmo-developer#3238]
## Description

On https://developer.nexmo.com/messaging/sms/code-snippets/receiving-an-sms

The code to display the image is:

```
<figure>
   <img src="/screenshots/smsInboundWebhook.png" alt="#{alt_text}">
</figure>
```

The alt text needs to be meaningful.

## What did you expect to happen?

Meaningful alt text needs to be included. This is a WCAG requirement.

## What actually happened?

Users of screen readers will not be able to understand what the image is trying to convey.

## Steps to reproduce:

Visit https://developer.nexmo.com/messaging/sms/code-snippets/receiving-an-sms with a screen reader, or a text only browser.

## Related resources

In this example, the offending code seems to be at https://github.com/Nexmo/nexmo-developer/blob/master/_documentation/en/messaging/sms/code-snippets/receiving-an-sms.md

I assume your Markdown converter is looking for an `alt_text` attribute in that code.

See https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html for information on alt text.

**Comment by edent** [comment]
Here's another one on https://developer.nexmo.com/messaging/us-short-codes/guides/2fa/python
![Broken alt text on a page](https://user-images.githubusercontent.com/837136/95135296-170c4d80-075c-11eb-914b-db90d64dd6b4.png)

Interestingly, the .md *has* alt text
https://github.com/Nexmo/nexmo-developer/blob/master/_documentation/en/messaging/us-short-codes/guides/2fa.md

So something in your build process is breaking.

**Comment by fabianrbz** [comment]
This has been fixed now
