### ISSUE TITLE
Incorrect response documentation for get-pricing endpoint.

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-developer#335]
The response breakdown for the call to get pricing in the docs actually details the response for 'get-balance'.

https://developer.nexmo.com/api/developer/account#pricing

**Comment by tommorris** [comment]
I can't replicate this. The screenshot below seems to show what it ought to show and matches the test API calls I've just made.

<img width="964" alt="screen shot 2017-09-18 at 15 29 22" src="https://user-images.githubusercontent.com/175/30547063-37dcdd48-9c86-11e7-96df-f293e5fd21ad.png">
