### ISSUE TITLE
Create SMS & Voice APIs tutorials for newbies & junior developers  (Vonage Voyager Application)

### ISSUE THREAD

**Issue by byruzyayandy1** [Nexmo/nexmo-developer#3458]
## Description

Create an  SMS & Voice APIs tutorials for newbies and junior developers, passionate about Vonage SMS & Voice APIs during hackathons, personal and professional projects.

## What did you expect to happen?

Make 30mins video tutorials on SMS & Voice APIs

**Comment by phazonoverload** [comment]
Thanks for this @byruzyayandy1. We actually do have lots of tutorials on our [Developer Blog](https://learn.vonage.com) for folks with a varying degree of technical confidence and experience. 

If you are opening an issue on this repo as part of the Vonage Voyagers application process, we're looking for feedback on the existing content - perhaps you've noticed an error, or something that doesn't seem right. If it's about the platform, you may open an issue on Nexmo/station instead. 

I'm going to close this issue and pop your application on hold. If you still want to be a part of the program, please open an issue which better answers the exercise in the next couple of weeks. If you have questions fire them over to voyagers@vonage.com - thanks!

**Comment by phazonoverload** [comment]
Just checking in on this. The issue doesn't have to be on this repo, but we won't be able to progress your application without a completed and accepted exercise. If you have any questions let me know here or at kevin.lewis@vonage.com
