### ISSUE TITLE
Verfiy Api - Cannot add a text to the body

### ISSUE THREAD

**Issue by seazy93** [Nexmo/nexmo-developer#3473]
## Description

I want to perform SMS Verification with vonage, but i need add to the end of the body an 11-character hash string for automic fill sms code. I see no option to do that? Any ideas for me?

## Related resources

https://developers.google.com/identity/sms-retriever/verify

**Comment by mheap** [comment]
Hey @seazy93

This can be accomplished using one of our custom templates. Please email support@nexmo.com with your API Key and target countries and they'll see what options are available
