### ISSUE TITLE
Global Messaging table should be sortable

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#354]
## Description

The table in https://github.com/Nexmo/nexmo-developer/blob/master/_documentation/messaging/sms/guides/global-messaging.md claims to be sortable but is not.

**Comment by tommorris** [comment]
@adambutler I'm going to close this as #356 has been merged. If we want sortable tables, the best thing seems to be to open that up as a separate PR and reference back to this issue.
