### ISSUE TITLE
Missing inbound voice callback information

### ISSUE THREAD

**Issue by peter-nexmo** [Nexmo/nexmo-developer#361]
## Description

Nexmo Developer is missing the details that we send in a callback for inbound calls for Forward to SIP or Forward to Phone

## What did you expect to happen?

These details need to be ported into Nexmo Developer: https://docs.nexmo.com/voice/voice-deprecated/call/status-codes

## Related resources

https://docs.nexmo.com/voice/voice-deprecated/call/status-codes

**Comment by adambutler** [comment]
Deprecated products are not present and are not being maintained on Nexmo Developer. We provide a [Legacy Documentation](https://developer.nexmo.com/legacy) page to highlight this content but have no plans for migrating it.

**Comment by peter-nexmo** [comment]
Forward to Phone and Forward to SIP are _not_ deprecated products and the callbacks will continue to be supported.
