### ISSUE TITLE
com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 77 path $..image_url

### ISSUE THREAD

**Issue by thang510023** [Nexmo/nexmo-developer#3662]
## Package in android build.gradle 

com.nexmo.android:client-sdk:2.8.0

## Description

I'm using conversation.sendCustomEvent and conversation.addCustomEventListener to get event working well, but conversation.getEvents has error com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 77 path $ .. image_url

My sample:

       String of message in debugging:
       {
           "chat_room_id": "CON-90bd2776-dac2-405b-9700-9d0051ea966d",
           "image_url": "https://pantok.s3.ap-northeast-2.amazonaws.com/profile/393839504_20210504104437.jpg",
           "message": "Hello ~~",
           "name": "Quyet Thang",
           "progress": 0,
           "send_time": "1620115311188",
           "type": "M",
           "user_id": "USR-0e38fe80-b69f-427f-9a5b-e564f65ebbf4"
        }

        HashMap<String, Object> customData = new Gson().fromJson(
                new Gson().toJson(message),
                new TypeToken<HashMap<String, Object>>() {
                }.getType()
        );

        nexmoConversation.sendCustomEvent("Custom:M", customData, new NexmoRequestListener<Void>() {
            @Override
            public void onError(@NonNull NexmoApiError nexmoApiError) {
                Log.e("LOG_TAG", "Send Custom Event: " + nexmoApiError.getMessage());
            }

            @Override
            public void onSuccess(@Nullable Void unused) {
                Log.e("LOG_TAG", "Send Custom Event: Success");
            }
        });

**Comment by pardel** [comment]
@thang510023 Sorry for the delay in answering this - meanwhile a new major version has been released. Could you please confirm that the bug still exists in the current v3.0.1? Many thanks!
