### ISSUE TITLE
Feature Request for Response for Verify Cancel Request

### ISSUE THREAD

**Issue by KittPhi** [Nexmo/nexmo-developer#3671]
Hello,

When trying to Cancel a Verification Request with Request ID, the Response is always "can't be cancelled, if if the default request "SMS->TTL->TTL" has completed. I would like to request that a more detailed and informative response be returned, depending on where in the process of Verification step is at.
Thank you for maintaining the site,
Kitt

Example Response:
{
  status: '19',
  error_text: "Verification request  ['df5d2720d93e481e84809a02ac10dc3b'] can't be cancelled now. Too many attempts to re-deliver have already been made."
}

**Comment by CaptCalli** [comment]
Hi @KittPhi! I work on the Developer Community team who run the Voyagers program - thanks so much for submitting this issue. 
For the sake of your Voyagers application - would you mind expanding as to why a more detailed and informative error text would be helpful? Could you also show how to recreate the steps to receive the same Response you have received ("can't be cancelled, if if the default request "SMS->TTL->TTL has completed")? 

Have a good day!

**Comment by pardel** [comment]
@CaptCalli we should probably close this issue as it's been open for 3 months now.
