### ISSUE TITLE
Add type parameter for Search available numbers request / add possible values in the response

### ISSUE THREAD

**Issue by sillein1** [Nexmo/nexmo-developer#370]
## Description

Please add _type_ parameter for **Search available numbers** section of page https://developer.nexmo.com/api/developer/numbers

**Parameter**: type
**Description**: Type of the number. Supported values: mobile-lvn, landline, landline-toll-free.

Also please add possible values of _type_ field in the json/xml response (instead of _mobile_): mobile-lvn, landline, landline-toll-free

Related JIRA-ticket:
https://nexmoinc.atlassian.net/browse/DEVAPI-179

## Related resources
Search available numbers on https://developer.nexmo.com/api/developer/numbers

**Comment by lornajane** [comment]
This seems like a useful addition, re-opening the issue.
