### ISSUE TITLE
Changes to REST API for Balance in Account API (Vonage Voyager Application)

### ISSUE THREAD

**Issue by ravgeetdhillon** [Nexmo/nexmo-developer#3763]
> Note: This issue is part of my Vonage Voyagers application.

## Description

This is in connection with the Account API to get the account balance.

## Current

Right now, when we send the following request,

```
GET https://rest.nexmo.com/account/get-balance?api_key=${apiKey}&api_secret=${apiSecret}
```

the following response is returned,

```json
{
   "value": 2.0,
   "autoReload": false
}
```

## Expected

This is a good response. However, it would be great if some more information is also returned, like the currency details - name and symbol.

A response like this would really help:

```json
{
   "value": 2.0,
   "currency": {
      "name": "euro",
      "symbol": "€"
   },
   "autoReload": false
}
```

## Why am I proposing this change?
- It prevents hardcoded symbols in the application
- It provides better maintainability across different applications
- You don't need to go through the docs to find what currency is related to the account balance
- If in future, Vonage decides to change the currency format, it will automatically be reflected across applications

**Comment by ClarisseNg** [comment]
Hi @ravgeetdhillon! I’m working on the Vonage Voyagers program, and I’m happy to accept this issue as part of your application. The repo owner may also have comments/questions, but they won’t impact your application. Chat soon!

**Comment by pardel** [comment]
@ravgeetdhillon Thank you for your suggestion. I'm going to close this issue as the current response structure reflects how the balance API works.
