### ISSUE TITLE
http://example.com/hg https://tfs.example.com/tfs	<= We’ll figure out which project next. Please check the URL and try again.. Please check the URL and try again

### ISSUE THREAD

**Issue by hanawa-suzuki** [Nexmo/nexmo-developer#392]
## Description

Please briefly describe what the issue is

## What did you expect to happen?

Delete section if this is not a bug.

## What actually happened?

Delete section if this is not a bug.
## Steps to reproduce:

Delete section if this is not a bug.

## Related resources

Route links & Documents paths that might be helpful. Delete section if not appropriate.

**Comment by Nakminea** [comment]
> ## Description
> Please briefly describe what the issue is
> 
> ## What did you expect to happen?
> Delete section if this is not a bug.
> 
> ## What actually happened?
> Delete section if this is not a bug.
> 
> ## Steps to reproduce:
> Delete section if this is not a bug.
> 
> ## Related resources
> Route links & Documents paths that might be helpful. Delete section if not appropriate.
