### ISSUE TITLE
Problems communicating with lex bot

### ISSUE THREAD

**Issue by egieseke** [Nexmo/nexmo-developer#394]
## Description

Unable to connect to AWS Lex bot from Nexmo using the Nexmo Lex Connector.  

Following the instructions here: https://github.com/Nexmo/nexmo-developer/blob/master/_documentation/voice/voice-api/guides/connecting-voice-calls-to-amazon-lex-bots.md

## What did you expect to happen?

Successful interaction with Lex bot.

## What actually happened?

Hear the introductory message from the nexmo call receiver, but then no interaction occurs with AWS Lex bot. 

## Related resources

Are there any log files provided by nexmo that may help determine the issue?
I am using a Nexmo trial account, should that be able to connect to Lex?

**Comment by sammachin** [comment]
Hi,

I can't see anything that should be causing that issue unless there is something in the parameters for your lex bot that are incorrect. Could you email devrel@nexmo.com with some more details like your NCCO and I'll take a deeper look. I'm gonna close this issue as its not really a docs thing.
