### ISSUE TITLE
NCCO should be in a concepts section under Voice

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#4]
http://nexmo-developer.herokuapp.com/voice/guides/ncco

**Comment by adambutler** [comment]
Conflicts with #5

**Comment by leggetter** [comment]
The description is lacking detail, but I'd actually say this is done.

<img width="970" alt="screen shot 2017-07-17 at 15 28 15" src="https://user-images.githubusercontent.com/328367/28272871-abc2a75a-6b04-11e7-9008-78194b95b568.png">

**Comment by tommorris** [comment]
We've moved NCCO into API reference. This is now redundant.
