### ISSUE TITLE
Stats for feedback

### ISSUE THREAD

**Issue by adambutler** [Nexmo/nexmo-developer#410]
## Description

It would be useful if we could see stats for Feedbot:

- [ ] Average score over time
- [ ] Resolved vs Unresolved
- [ ] Top positive pages
- [ ] Top negative pages
- [ ] Most commented

**Comment by lornajane** [comment]
Definitely this would be useful, I have been asking about it already.

**Comment by lornajane** [comment]
Hey @mheap do you want to keep this open? I feel like the summary bits you added have covered most of what I'd have asked for on this

**Comment by mheap** [comment]
Let's close for now. If we need more stats for the dashboard we can build APIs
