### ISSUE TITLE
Add SIP to overview pages

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#453]
## Description

It's presently quite difficult to find out SIP documentation. I'd suggest we bring it to the surface by adding it to the Voice section.

<img width="434" alt="screen shot 2017-11-02 at 13 55 30" src="https://user-images.githubusercontent.com/328367/32329666-961ecbce-bfd5-11e7-8688-bead05e023ba.png">

**Comment by lornajane** [comment]
This seems important to me. Re-opening.

**Comment by vipulgupta2048** [comment]
@lornajane @leggetter Hey, I would like to solve this out. Seems simple enough. Anything I should know before jumping in.

**Comment by vipulgupta2048** [comment]
https://github.com/Nexmo/nexmo-developer/tree/master/_documentation/voice/sip
Is it this one?

**Comment by leggetter** [comment]
We're having some internal discussion about information architecture. As such, I'm closing this one.

Thanks for your interest in helping, @vipulgupta2048.
