### ISSUE TITLE
Need help in creating advanced conference call with Nexmo using PHP

### ISSUE THREAD

**Issue by paidee** [Nexmo/nexmo-developer#454]
# I can't get this code to work

I assume that it's because I don't know how to populate these fields from the code below, Can someone please help?

$to = $request['to']; //The endpoint being called
    $from = $request['from']; //The endpoint you are calling from
    $uuid = $request['uuid']; //The unique ID for this Conversation
<?php

$method = $_SERVER['REQUEST_METHOD'];
$request = array_merge($_GET, $_POST);

switch ($method) {
  case 'GET':

    //Retrieve with the parameters in this request
    $to = $request['to']; //The endpoint being called
    $from = $request['from']; //The endpoint you are calling from
    $uuid = $request['uuid']; //The unique ID for this Conversation

    //Send the header
    header('Content-Type: application/json');

    //For more advanced Conversations you use the paramaters to personalize the NCCO
    //Dynamically create the NCCO to run a moderated conversation from your virtual number
    if( $from == "441632960960")
      $ncco='[
              {
                "action": "conversation",
                "name": "nexmo-conference-moderated",
                "endOnExit": "true",
                "record": "true"
              }
             ]';
    else
      $ncco='[
        {
          "action": "talk",
          "text": "Welcome to a Nexmo moderated conference",
          "voiceName": "Amy"
        },
        {
          "action": "conversation",
          "name": "nexmo-conference-moderated",
          "startOnEnter": "false",
          "musicOnHoldUrl": ["https://nexmo-community.github.io/ncco-examples/assets/voice_api_audio_streaming.mp3"]
        }
      ]';

    echo $ncco;
    break;
  default:
    //Handle your errors
    handle_error($request);
    break;
}

## What did you expect to happen?

Delete section if this is not a bug.

## What actually happened?

Delete section if this is not a bug.

## Steps to reproduce:

Delete section if this is not a bug.

## Related resources

Route links & Documents paths that might be helpful. Delete section if not appropriate.

**Comment by adambutler** [comment]
Hi @paidee, sorry for the slow reply but you've raised an issue against our documentation platform repository and we don't generally provide product support here.

I'll try and answer your question anyway but if you have got any further questions I'd like to ask that you contact support at support@nexmo.com.

These values are sent to you with [Webhooks](https://developer.nexmo.com/concepts/guides/webhooks) from Nexmo when a call is answered. These values are part of the payload that Nexmo send and can be accessed through the `$request` object.

Hope this helps, I'll close the issue. If you have any further trouble drop the support team a question on the email above.
