### ISSUE TITLE
Ensure all code samples are using supported libraries where possible

### ISSUE THREAD

**Issue by tommorris** [Nexmo/nexmo-developer#48]
- [ ] https://developer.nexmo.com/voice/guides/create-conferences
- [ ] https://developer.nexmo.com/voice/guides/record-calls-and-conversations
- [ ] https://developer.nexmo.com/voice/guides/outbound-calls
- [ ] `creating-a-custom-call-or-conversation-for-each-user`

Anything containing a `generate_jwt` function call probably needs to get splatted too.

**Comment by leggetter** [comment]
I think we need to do a full review of all the content and identify all the code examples that require updates.
