### ISSUE TITLE
account/settings - api-secret in documentation but not in example

### ISSUE THREAD

**Issue by angel-popov** [Nexmo/nexmo-developer#494]
## Description

On page https://developer.nexmo.com/api/developer/account
in description of 'settings' request,
table with response mentioned field api-secret, but it is not shown in the example.

## What did you expect to happen?

api-secret should not be mentioned in the documentation because it is not in the response
```
Request:curl -s -X POST 'https://rest.nexmo.com:443/account/settings' -H 'Content-type:application/x-www-form-urlencoded' -d "moCallBackUrl=http://example.com&drCallBackUrl=http://example.com&apiSecret=opala&api_key=xxxxxx&api_secret=xxxxxxx"
Response:{"mo-callback-url":"http://example.com","dr-callback-url":"http://example.com","max-outbound-request":30,"max-inbound-request":30}

**Comment by tommorris** [comment]
Thank you @angel-popov! The fix for this has been merged and will be live on the site shortly. 🎉
