### ISSUE TITLE
curl -X "POST" "https://rest.nexmo.com/sms/json" \   -d "from=Nexmo" \   -d "text=A text message sent using the Nexmo SMS API" \   -d "to=TO_NUMBER" \   -d "api_key=API_KEY" \   -d "api_secret=API_SECRET"

### ISSUE THREAD

**Issue by loveppzax** [Nexmo/nexmo-developer#509]
-X "POST" "https://rest.nexmo.com/sms/json" \
  -d "from=Nexmo" \
  -d "text=A text message sent using the Nexmo SMS API" \
  -d "to=TO_NUMBER" \
  -d "api_key=API_KEY" \
  -d "api_secret=API_SECRET

**Comment by adambutler** [comment]
Sorry, but we've not understood this issue.

It's possible you may have created it by accident or it has not got enough detail for us to answer or investigate.

To keep things tidy we're going to close it for now. If you are still experiencing issues with our Nexmo Developer documentation tooling or content then feel free to [open another issue](https://github.com/Nexmo/nexmo-developer/issues/new) providing more detail as outlined in the template.

Alternately if your issue does not relate to our documentation then you can:

- Visit our [Knowlegebase](https://help.nexmo.com)
- Read the documentation at [Nexmo Developer](https://developer.nexmo.com)
- Check our current [platform status](https://www.nexmostatus.com)
- Email Support at [support@nexmo.com](mailto:support@nexmo.com)
