### ISSUE TITLE
PHP sample code missing in section 3

### ISSUE THREAD

**Issue by olivier-nexmo** [Nexmo/nexmo-developer#514]
## In section 3, there is some code missing

// work with get or post
$request = array_merge($_GET, $_POST);
 
## 

If you don't add this line, you won't be able to get the parameters in your answer_url (from, to, uuid).
unless you replace $request[] with $_REQUEST[]

Note: in section 4, the code is correct.

**Comment by adambutler** [comment]
What page is this in reference to?

**Comment by olivier-nexmo** [comment]
https://developer.nexmo.com/voice/voice-api/guides/inbound-calls

**Comment by adambutler** [comment]
Fixed the issue, we've got all new code examples coming soon 🙌
