### ISSUE TITLE
Syntax error in Record NCCO example

### ISSUE THREAD

**Issue by fjkattan** [Nexmo/nexmo-developer#523]
## Description

"endOnSilence" should be an integer, but example shows "3" in quotes.  Just need to remove the quotes around the "3" from the sample code below.

## Related resources

[
  {
    "action": "record",
    "eventUrl": ["https://example.com/recordings"],
    "endOnSilence": "3"
  },
  {
    "action": "connect",
    "eventUrl": ["https://example.com/events"],
    "from":"447700900000",
    "endpoint": [
      {
        "type": "phone",
        "number": "447700900001"
      }
    ]
  }
]

**Comment by adambutler** [comment]
Fixed by 2cb9d2c5d87a565c2c9e352a974ff850a0d12e31
