### ISSUE TITLE
SMS API reference "Query Parameter" values should be in POST body

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#543]
## Description

`api_key` and `api_secret` should be in the body POST parameters. Likely as should `sig`.

## What did you expect to happen?

Remove Query Parameter heading and place params in POST body.

**Comment by lornajane** [comment]
@leggetter There's an open PR for this, but the issue was closed by Stalebot and I'm a bit stuck on the _why_ for this request. Does the API support both query parameters and body parameters and it would be better to put it in the body for POST requests? What do you think?
