### ISSUE TITLE
Python signature verification code is bad.

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-developer#559]
## Description

The [Python code](https://github.com/Nexmo/nexmo-developer/blob/master/_documentation//concepts/guides/signing-messages.md) demonstrating how to generate/validate a signature is:

a) Really bad
b) Broken

Signatures can be generated transparently using the Nexmo client library. Verifying signatures is as simple as: 

```python
import nexmo

client = nexmo.Client(signature_secret=NEXMO_SIG_SECRET, signature_method='sha1')
print(client.check_signature(params))  # True if the signature secret is correct.
```

(If we want code demonstrating how to generate a signature without the client lib, it could be extracted from nexmo-python.)

**Comment by lornajane** [comment]
Pretty sure we still want to fix this, re-opening.

**Comment by lornajane** [comment]
@judy2k Any danger of you getting to this? It came up yesterday in a customer query, the other code samples look good which might give you some help if you need it?

**Comment by leggetter** [comment]
I _thought_ this was part of the library spec?

**Comment by lornajane** [comment]
No we still really do need this, sorry Stalebot

**Comment by lornajane** [comment]
Code examples were removed so this is sort of fixed although new code samples are still a work in progress.
