### ISSUE TITLE
Anchor links in WebSocket feature Node code examples

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#586]
## Description

It looks like a parser/filter is adding anchors to code examples.

See:

<img width="867" alt="screen shot 2018-02-26 at 17 14 38" src="https://user-images.githubusercontent.com/328367/36684659-f6ed9b44-1b18-11e8-8c11-a9be753dd628.png">

**Comment by adambutler** [comment]
Fixed by 9f377c21
