### ISSUE TITLE
Metadocs: what needs documenting about Nexmo Developer?

### ISSUE THREAD

**Issue by tommorris** [Nexmo/nexmo-developer#595]
We will likely soon need some documentation for how Nexmo Developer works...

* [ ] What “environment redirects” do
* [ ] We should document in write-the-docs preferred libraries e.g. Flask, Express, Sinatra, requests, and use of Nexmo supported libraries. (Probably for @tommorris)
* [x] List of filters and roughly what they do
* [ ] What external integrations do we have? (Bugsnag, search, logging etc.)
* [ ] How to log into the admin site

**Comment by lornajane** [comment]
This would be useful, re-opening.

**Comment by tbedford** [comment]
There is some material here:

https://developer.nexmo.com/contribute/guides/platform

**Comment by tbedford** [comment]
Also one for the new NDP developer to take a look at. I think there are probably still things we need to document about Platform so removing stale tag for now.

**Comment by mheap** [comment]
@benhayehudi One for you I think. This information could go in the `Administration` section under `/contribute`
