### ISSUE TITLE
Pricing by country response is incorrect

### ISSUE THREAD

**Issue by timcraft** [Nexmo/nexmo-developer#624]
The keys in the pricing by country [JSON/XML Response examples](https://developer.nexmo.com/api/developer/pricing#response) don't match what's returned by the API (and documented further down under [Keys and Values](https://developer.nexmo.com/api/developer/pricing#keys-and-values) and [Common elements in responses](https://developer.nexmo.com/api/developer/pricing#common-elements-in-responses)).

Keys should be e.g. countryCode instead of country, dialingPrefix instead of prefix, defaultPrice instead of mt, networkCode instead of code, price instead of mtPrice.

**Comment by lornajane** [comment]
We should check/fix this, re-opening

**Comment by timcraft** [comment]
@lornajane Hey! Thanks for re-opening. I started #787 so this didn't get lost because of our over-eager bot friend. The pull request fixes the keys that are in the existing code samples, but there are some additional keys in the responses which could also be added.

**Comment by timcraft** [comment]
Fixed by #916
