### ISSUE TITLE
Heroku > postdeploy doesn't seem to be working for production

### ISSUE THREAD

**Issue by adambutler** [Nexmo/nexmo-developer#665]
## Description

See note at https://github.com/Nexmo/nexmo-developer/wiki/Algoia-Search#indexing

**Comment by mheap** [comment]
Still pending

**Comment by mheap** [comment]
Closing as we don't want a post-deploy hook (which only runs after the initial deploy).

We could reindex as part of the deploy process, but that could get expensive quickly. Instead, we're evaluating a periodic reindex option
