### ISSUE TITLE
Add "Send a Unicode SMS" Building Block

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#694]
Sending a unicode SMS is a common piece of functionality that would benefit from having a building block.

We should also consider linking to it from here https://developer.nexmo.com/messaging/sms/guides/concatenation-and-encoding or embedding the building block code an an *example* within the context of the page.

**Comment by tbedford** [comment]
Good idea. See also issue #701.

**Comment by tbedford** [comment]
Code (for Python here):

https://github.com/nexmo-community/nexmo-python-quickstart/blob/master/sms/send-an-sms-with-unicode.py

**Comment by tbedford** [comment]
See PR #754 for fix.
