### ISSUE TITLE
Try-it-Out component for SMS concatenation has issues

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#725]
## Description

The try-it-out on [this page](https://developer.nexmo.com/messaging/sms/guides/concatenation-and-encoding#maximum-number-of-characters
) has an issue:

If you type a '{' character or other character from GSM extended table it will flag that as requiring a type of 'unicode' whereas a type of 'text' is fine. However, note that a character from the GSM extended table does require two characters (ESC + char). In short, characters from GSM standard and extended table are message `type` of `text`. Only characters outside the GSM range require a `type` of `unicode`.

## Related resources

* https://developer.nexmo.com/messaging/sms/guides/concatenation-and-encoding#maximum-number-of-characters
* #701

**Comment by tbedford** [comment]
Assigned to @leggetter until NDP developer can be assigned.

**Comment by leggetter** [comment]
Maybe just a matter of adding characters to the `safeCharacters` variable https://github.com/Nexmo/nexmo-developer/blob/master/app/javascript/packs/Concatenation.jsx#L5-L29

**Comment by lornajane** [comment]
This behaviour seems to be well documented at least! https://github.com/Nexmo/nexmo-developer/blob/master/app/javascript/packs/Concatenation.jsx#L32
