### ISSUE TITLE
NDP web application issues

### ISSUE THREAD

**Issue by tbedford** [Nexmo/nexmo-developer#761]
## Description

A couple of issues I'd like to capture here. 

1) Table-of-contents (TOC) does not scroll.

2) Material in TOC can sometimes have random order. For example in Messages and Workflows the subsection Messages sometimes is displayed first, and then other times Workflows is displayed first. This is confusing for users. 

3) `navigation_weight` does not seem to work sometimes as expected. For example, in the Guides section here: https://developer.nexmo.com/contribute/guides Weights are specified, but never seem to be applied.

**Comment by tbedford** [comment]
@leggetter @hughhopkins - FYI

**Comment by tbedford** [comment]
Closing, as I believe @mheap is working on these.

**Comment by mheap** [comment]
@tbedford Can you make sure that we have tickets for each of these items if needed?

**Comment by tbedford** [comment]
1) Was fixed by @leggetter some time ago. Can't see the PR though.
2) Was fixed by me by tweaking a weighting file in NDP - navigation.yml.
3) Was fixed by you #910.
