### ISSUE TITLE
Why isn't a guide for the Stitch demo Android on the Nexmo-Developer portal?

### ISSUE THREAD

**Issue by Semeruk** [Nexmo/nexmo-developer#784]
## Description

I want to have a guide to walk through Stitch Demo Android, can someone help me with this?

**Comment by ericgiannini** [comment]
I agree with you. @Semeruk I will follow up with you asap.

**Comment by ChrisGuzman** [comment]
It's Hey @Semeruk the link is in the overview page: https://developer.nexmo.com/stitch/overview#references

The direct link to the demo is here: https://github.com/Nexmo/stitch-demo-android

**Comment by ericgiannini** [comment]
@ChrisGuzman This issue needs to be reopened. https://developer.nexmo.com/stitch/overview#references is not what @Semeruk is requesting.

**Comment by ChrisGuzman** [comment]
@Semeruk does the readme for the repo https://github.com/Nexmo/stitch-demo-android cover what you're looking for?

**Comment by ericgiannini** [comment]
[DEVX-290](https://nexmoinc.atlassian.net/browse/DEVX-290) is set up to address this issue.

**Comment by ericgiannini** [comment]
@Semeruk We will prioritize guides and get them set up for you asap. Thanks for this issue.

**Comment by Semeruk** [comment]
@ericgiannini is right. 
The guide is a bit different from the source code, for example Android Networking is used in https://github.com/Nexmo/stitch-demo-android, guide didn't cover it. 
Also that project has connection to gateway server which are also not described in walkthrough guide.
I'm not judging I just want to know more.

And here https://developer.nexmo.com/stitch/in-app-messaging/guides/3-utilizing-events/android#2-3-creating-the-chatadapter-and-viewholder
in this method: 

`@Override
    public int getItemCount() {
        return messages.size();
    }`

Why isn't there events.size() instead of messages.size()?

P.S. I don't have access to that link @ericgiannini

**Comment by ericgiannini** [comment]
n/p It is an internal link. If you have a problem with that `getItemCount()` method, please open up a different ticket so that it may be addressed separately. We are working on the walkthrough guide. We are really appreciative of your feedback!

**Comment by Semeruk** [comment]
Thank you!

**Comment by ChrisGuzman** [comment]
Thanks for the suggestion, the team will work on a guide or README with full instructions on how to setup a server and make networking requests.

**Comment by ericgiannini** [comment]
@Semeruk It has been delivered.
