### ISSUE TITLE
Add get-phone-pricing endpoints?

### ISSUE THREAD

**Issue by timcraft** [Nexmo/nexmo-developer#786]
There used to be a couple of endpoints for retrieving pricing for specific numbers:

* rest.nexmo.com/account/get-phone-pricing/outbound/sms?phone=NUMBER
* rest.nexmo.com/account/get-phone-pricing/outbound/voice?phone=NUMBER

These aren't currently documented in the Pricing API Reference.

Are they still supported?

**Comment by timcraft** [comment]
* nexmo-ruby used to implement them (removed in v5.0.0)
* nexmo-node implements them in `getPhonePricing`, with credentials in path 😳
* nexmo-php does not implement them
* references to the old nexmo-ruby methods were removed in 37c8fcb7 and 98ec2880

**Comment by lornajane** [comment]
This is so interesting. I'm working on Account API docs in the next few weeks, will poke at the API while I am there and try to find out what we have (and what we want to document, which might be different!)

**Comment by timcraft** [comment]
They're definitely still working, this works for me:

```ruby
require 'nexmo'

params = {api_key: 'TODO', api_secret: 'TODO', phone: 'TODO'}

uri = URI('https://rest.nexmo.com/account/get-phone-pricing/outbound/voice')
uri.query = Nexmo::Params.encode(params)

response = Net::HTTP.get_response(uri)

puts response.code
puts response.body
```

What isn't clear is whether they should be documented and supported in client libraries (or not).

**Comment by timcraft** [comment]
Doubt these bots will be taking over anytime soon.

@lornajane @mheap Did you manage to find anything out about these endpoints?

**Comment by mheap** [comment]
I haven't looked in to it yet. As no-one's mentioned that they're missing I'm not sure they're used
