### ISSUE TITLE
How come there is no guide one how to implement the CallKit extension in Nexmo-Stitch?

### ISSUE THREAD

**Issue by Semeruk** [Nexmo/nexmo-developer#789]
## Description

I want to implement the CallKit into Nexmo-Stitch, are there any thoughts/examples on this? I will be very pleased! Thanks.

**Comment by ericgiannini** [comment]
Thanks, @Semeruk ! ;) We have discussed a guide with an extension for CallKit into Nexmo-Stitch. I will generate a ticket but the earliest I can provide a guide is Friday this week or Monday next week.

**Comment by Semeruk** [comment]
@ericgiannini okay, so an investigation from my side might bring some good stuff too I believe!
Appreciate your help @ericgiannini !

**Comment by ChrisGuzman** [comment]
This is a good idea for a blog post. @ericgiannini will look into this. Thanks for the suggestion!

**Comment by ericgiannini** [comment]
@Semeruk I wanted to update you. We decided that CallKit would be a great idea for a blog post! Unfortunately, we have no set timeframe on when the blog post will be published.

**Comment by ericgiannini** [comment]
@Semeruk CallKit has been integrated. Whether or not it will appear in a blog is still an open question. Please let us know whether you have any other requests for Stitch!
