### ISSUE TITLE
Add a Print Stylesheet

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#795]
## Description

When I tried to print a page from our lovely, well presented docs to refer to, it created a mess (see attached), unlike what I saw on screen
[Nexmo Developer _ Overview.pdf](https://github.com/Nexmo/nexmo-developer/files/2166888/Nexmo.Developer._.Overview.pdf)

## What did you expect to happen?

A clear and well-formatted print of the content I could see on screen should be printed.

## What actually happened?
See attached PDF!

## Steps to reproduce:

Choose Print on any page

**Comment by lornajane** [comment]
I still think this would be an excellent addition to a good developer experience. Not stale.

**Comment by lornajane** [comment]
Beware if you pick this up any time soon that we're about to launch a redesign so you're aiming for https://nexmo-developer-staging-pr-825.herokuapp.com/ in style (it's in the `volta` branch).  Or just wait for the redesign to land.

**Comment by ms10398** [comment]
@lornajane I want to try to solve this issue

**Comment by AraanBranco** [comment]
example of how the pdf was
[Nexmo Developer_with_colors.pdf](https://github.com/Nexmo/nexmo-developer/files/2497735/Nexmo.Developer_with_colors.pdf)

**Comment by ssiddhantsharma** [comment]
@ms10398 I felt the same way when someone took my issue! It is wrong and disrespectful to take another developer's issues.

**Comment by lornajane** [comment]
Fixed by #1132
