### ISSUE TITLE
Platform selectors in Stitch QuickStarts don't update the URL

### ISSUE THREAD

**Issue by AlexLakatos** [Nexmo/nexmo-developer#801]
## Description

Changing the platform on one of the Stitch Quick Start pages updates the content to the correct platform but the URL isn't updated anymore. https://developer.nexmo.com/stitch/in-app-messaging/guides/1-simple-conversation/javascript

## What did you expect to happen?

When I click on "Android", the URL gets updated to https://developer.nexmo.com/stitch/in-app-messaging/guides/1-simple-conversation/android

## What actually happened?

The URL isn't updated.

## Steps to reproduce:

1. Go to https://developer.nexmo.com/stitch/in-app-messaging/guides/1-simple-conversation/javascript
2. Click on "Android"

**Comment by lornajane** [comment]
This bug is still present, who would be a good person to look at this? @ChrisGuzman would this be you or can you nominate a qualified individual?

**Comment by ChrisGuzman** [comment]
Yeah this is something I should tackle. I'll add it to my backlog
