### ISSUE TITLE
The Stitch SDK JS docs interfere with the browser back button

### ISSUE THREAD

**Issue by AlexLakatos** [Nexmo/nexmo-developer#832]
## Description
The Stitch SDK JS docs interfere with the browser back button

## Steps to reproduce:
1. Go to https://developer.nexmo.com/stitch/in-app-voice/guides/enable-audio/
2. At the bottom of the page, click the SDK docs link
3. Hit the browser back button

The URL bar updates with the correct URL, but the page remains the same.

**Comment by lornajane** [comment]
I think this got fixed - at least, I can't reproduce it now.
