### ISSUE TITLE
Handle User Input with DTMF - Java Example Broken

### ISSUE THREAD

**Issue by cr0wst** [Nexmo/nexmo-developer#895]
## Description

The building block for "Handle User Input with DTMF" for Java does not work correctly. The response that gets sent to `webhooks/dtmf` has a json body. Java users will need to create an additional object in order to deserialize the json and get the `dtmf` property.

Raising an issue because I'm not entirely sure where this extra class should live in the documentation. Maybe I update the Java library to include it as an added functionality?

## What did you expect to happen?

I expected the correct digit to be read back.

## What actually happened?

`null` was read back.

## Steps to reproduce:

Follow the building block example and call your number.

**Comment by ChrisGuzman** [comment]
The [java yml file](https://github.com/Nexmo/nexmo-developer/blob/master/_examples/voice/handle-user-input-with-dtmf/java.yml) could include a `client` section like the [ruby yml file](https://github.com/Nexmo/nexmo-developer/blob/master/_examples/voice/handle-user-input-with-dtmf/ruby.yml#L10-L13) does

and in that section it could point to a different class that does the parsing and then the building block code can reference the method/class from the `client` section

**Comment by ChrisGuzman** [comment]
then the building block page would have a "initialize your dependencies" section

**Comment by cr0wst** [comment]
Hmm. I'm not opposed to this, but I think there needs to be a bit of explanation that this class needs to be created rather than just another section of code.

Even a small explanation above it like:

---

Create the following `DtmfPayload` class:

```java
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;

@JsonIgnoreProperties(ignoreUnknown = true)
public class DtmfPayload {
    private String dtmf;

    @JsonProperty("dtmf")
    String getDtmf() {
        return this.dtmf;
    }

    public static DtmfPayload fromJson(String json) {
        try {
            return new ObjectMapper().readValue(json, DtmfPayload.class);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return new DtmfPayload();
    }
}
```

**Comment by ChrisGuzman** [comment]
Couldn't that be an inner class in DtmfInput.java?

**Comment by cr0wst** [comment]
Yeah I can probably figure out a way to do that. Jackson doesn't play nicely with inner classes because the compiler adds a hidden constructor that wipes out the no-arg constructor. I _think_ it works with static classes, though. I'll play around with it.

**Comment by cr0wst** [comment]
Hmm.

I'm not _quite_ satisfied with this:
![image](https://user-images.githubusercontent.com/8314724/44120430-54b14e78-9fea-11e8-88d9-04aacfd03352.png)
It seems unclear that you're adding an inner static class to an already existing class. I _think_ it's because we use phrases like "Add the following to SomeClass.java" as a file, instead of as a class.
