### ISSUE TITLE
Is it possible to record DTMF Input at any random point in a call?

### ISSUE THREAD

**Issue by penland365** [Nexmo/nexmo-developer#900]
I'm not 100% sure this is the correct forum, but I thought I would describe my question and hopefully someone could point me in the right direction.

Our current workflow is as follows:

1. A customer places a phone call to a nexmo number
2. Our `/answers` webhook returns an NCCO with two options, record and connect. The connect is a websocket connection.
3. Our WS endpoint takes ownership of the call, interacting with a custom bot through a lot of moving pieces. 

So far this has worked flawlessly for us. However, we have a new feature would like to include that requires inputting longer numbers like a credit card. Ideally, we would like to rely on DTMF to handle this input. However, from my reading of the documentation, this does not seem possible at this time, as the NCCO has already "successfully completed" in connecting to the WS. I have tried merely terminating the stream with a fallback event URL, but as this doesn't meet one of the 5 listed states for a fallback URL, the call itself just terminates. It is not possible for us to put this input at a specific point in the call, so taking these numbers would have to be ad hoc.

Any recommendations or thoughts on how to proceed? Thanks!

**Comment by ChrisGuzman** [comment]
Hi there!

You're correct that currently it's not possible to record DTMF once the calls has been connected to a websocket. 

There currently aren't any work-arounds for this, but we've relayed your feedback to the team as a feature request.

If you have more questions about using Nexmo you can reach out to us by:

- Joining our [community slack](https://developer.nexmo.com/community/slack)
- contacting support at support [at] nexmo [dot] com
- contacting the Developer Relations team at devrel [at] nexmo [dot] com

**Comment by penland365** [comment]
@ChrisGuzman Thank you so much for the feedback!
