### ISSUE TITLE
Error: Bundler::RubyVersionMismatch: Your Ruby version is 2.5.0, but your Gemfile specified 2.5.1

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#927]
## Description

Trying NDP for the first time in a while.

```sh
git pull origin master
docker-compose up --build

Error: Bundler::RubyVersionMismatch: Your Ruby version is 2.5.0, but your Gemfile specified 2.5.1
```

So started a fresh and got the same error.

I've since messed about with a few docker-type things (not really knowing what I'm doing) and eventually got it working. But likely worth somebody else trying NDP out from fresh to see if the Ruby update has broken something.

Notes on things I have done:

Dockerfile change:

```
# Base image:
FROM ruby:2.5.1
```

**Comment by lornajane** [comment]
I can confirm this is a problem
