### ISSUE TITLE
Messages and Workflows API error definitions

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#941]
## Description

I can't find the Errors codes and reasons in the messages workflow. There's a link to http://localhost:3000/api/messages-and-workflows-apis/workflows#errors with the wording "The error code. See Errors for a table of descriptions." but the Errors link goes to an internal anchor that isn't there and I'm not sure where it should point to.

## What did you expect to happen?

See a table of error reasons and codes

## What actually happened?

Doesn't link to anywhere

**Comment by tbedford** [comment]
Also applies to Messages API.
