### ISSUE TITLE
Response fields rendering for XML schemas

### ISSUE THREAD

**Issue by timcraft** [Nexmo/nexmo-developer#950]
There's a bug showing up in the "Response Fields" section of the [SMS API docs](https://developer.nexmo.com/api/sms#send-an-sms). The table under "Response Fields" includes a "messages" field, which is incorrect:

![bug](https://user-images.githubusercontent.com/896098/45423973-f19bdb00-b68c-11e8-8150-48b3c3cdccda.gif)

This is happening because there are two sets of properties being rendered, one for each format. The relavent view code is in `app/views/open_api/_response_descriptions.html.erb`

Wrapping the list items in `<div class="js-format" data-format="<%= format %>">` works for toggling between the two formats, but doesn't address the issue that the fields for XML are incorrect.

Not sure if the "correct" fix is to hide the response fields for XML, or to fix the view code to list the nested XML properties when toggling between the two formats.

**Comment by timcraft** [comment]
Fixed in 5ad927a2 I think.

**Comment by mheap** [comment]
Yep! Cheers Tim
