### ISSUE TITLE
Building Blocks: Cannot expand dependencies sections

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#974]
## Description

Example here https://nexmo-developer-staging-pr-825.herokuapp.com/voice/voice-api/building-blocks/earmuff-a-call the building blocks have expandable dependencies sections - the arrow is far to the right and isn't "clickable".

## What did you expect to happen?

Be able to click to expand these sections

## What actually happened?

Nothing

**Comment by BennyZ28** [comment]
You should be able to now? I just could

**Comment by lornajane** [comment]
I'm sorry, there's nothing to "click" on. I've attached a screenshot of what I see.
![screenshot from 2018-09-25 16-43-25](https://user-images.githubusercontent.com/172607/46026032-39d1e900-c0e2-11e8-96f2-fc191c37c9e7.png)

**Comment by mheap** [comment]
There's also an issue with Turbolinks for this too, as the Volta JS doesn't reapply after "refresh"

**Comment by BennyZ28** [comment]
Right, ok, I was confusing this with an issue we had of accordions actually
being broken even on click. I can add tabindex to those so they show up.

**Comment by lornajane** [comment]
Looks like there has been more work on this - I now see a label on the heading of each expandable section but "clicking" it doesn't make the expand happen.

**Comment by mheap** [comment]
@kmanktelow Playing with this it looks like we can expand sections, but not collapse them again. Should we be able to?

Could we also move the dropdown arrow to be a `::before` rather than an `::after`? It's too far away at the moment and people haven't realised that they can click to expand

**Comment by BennyZ28** [comment]
To be honest I've actually never seen an accordion with the arrow on the
left, so rather than this just being a Volta pattern I'd consider this a
standard UX pattern that I wouldn't go against. If the concern is the user
understanding that this is an accordion, obviously first I'd test it, but
then there are other solutions we can look into like a background, without
moving the arrow.

**Comment by mheap** [comment]
Fixed
