### ISSUE TITLE
Numbers is now a top level item

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#976]
## Description

We moved Numbers to be a top-level menu item so it will need an icon

**Comment by lornajane** [comment]
What's the best way to keep the branches in sync? @mheap any thoughts (no squashing at this point please!), there are conflicts according to GitHub.

**Comment by mheap** [comment]
Keep merging `master` in to `volta` and resolving conflicts I guess. It's a pain point of long lived branches

On this point in particular though, we may not need it if we go through with the supporting services reorganisation

**Comment by BennyZ28** [comment]
Fixed
