### ISSUE TITLE
Make right hand bar dark on API Docs

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#978]
## Description

The right hand pane on API docs is normally dark, but ours is light now https://nexmo-developer-staging-pr-825.herokuapp.com/api/voice

## What did you expect to happen?

Something more like our existing API docs on the right hand pane background: https://developer.nexmo.com/api/voice

**Comment by BennyZ28** [comment]
I actually changed it from a dark background to a light background to improve readability, which came up in a conversation with @mheap. Stripe also has it lighter than you did before.

**Comment by mheap** [comment]
I don't feel strongly either way about this. Worth gathering more external feedback?

**Comment by BennyZ28** [comment]
This for me classifies as a non-blocker in any case

**Comment by lornajane** [comment]
Let's just leave this as-is, I don't love it but it definitely shouldn't block progress!
