### ISSUE TITLE
API Reference Page Layout (discussion)

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#980]
## Description

The grid layout on the APIs page makes (IMO and I know this is subjective!) it harder to find things since you need to scan all over the page rather than read a simple list.

Compare the existing version https://developer.nexmo.com/api with the proposed version https://nexmo-developer-staging-pr-825.herokuapp.com/api

A few people have mentioned this and I think we need to discuss this more. The same could apply to the tutorials page https://nexmo-developer-staging-pr-825.herokuapp.com/tutorials which is "pinterest style" on both versions of the site

**Comment by sammachin** [comment]
The grid style is ok IMO but I really don't like the way stuff doesn't line up and is a random size, these need to be fixed height tiles.

**Comment by mheap** [comment]
This is being worked on in #1284
