### ISSUE TITLE
Main content does not scroll

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#984]
## Description

When visiting a documentation page, the main content pane does not scroll on any of:
* spacebar
* PageDown
* vimium controls, `j` or `d` or `G`

## What did you expect to happen?

Scroll down like any other web page so I can see content below the page

## What actually happened?

No scrolling. Some of the keys work after "focussing" the content pane.  This is minimum four key presses for a vimium user so is not a solution. The main content should have focus on load.

## Steps to reproduce:

Go to any page with the frames layout, try to scroll down without pointing to the content area with a mouse or trackpad.

## Related resources

Pages without frames are fine (e.g. https://nexmo-developer-staging-pr-825.herokuapp.com/tools)
Documentation pages with frames are not working as expected (e.g. https://nexmo-developer-staging-pr-825.herokuapp.com/account/guides/numbers)
API docs pages are also not working as expected (e.g. https://nexmo-developer-staging-pr-825.herokuapp.com/api/voice)

**Comment by BennyZ28** [comment]
@lornajane this should have been fixed now, do you still have the problem?

**Comment by lornajane** [comment]
If I click on the links from this issue, I have no problem. If I click on the same destinations from a link inside the site, so in a page or in a sidebar menu or something, then I have no scrolling ability. I'm not sure how that's even possible, but that's what I'm seeing.

**Comment by BennyZ28** [comment]
Ok I think we need help from @mheap then, I put the scrolling in the refresh() method but this sounds like it's not being called when visiting internal links maybe?

**Comment by mheap** [comment]
I've just pushed a fix for this up. The code was being run fine, but it looks as though `.focus()` isn't enough for Vimium. Changing the handler to `.click()` seems to be working

**Comment by marklewin** [comment]
Everything seems to be working well for me.

**Comment by mheap** [comment]
✅
