### ISSUE TITLE
Order of feedback icons

### ISSUE THREAD

**Issue by marklewin** [Nexmo/nexmo-developer#996]
## Description

The feedback icons appear (to me and @mheap) to be in the wrong order. I just naturally expect the first one to be happy and the second one to be sad (i.e. “Was this documentation helpful?” “Yes/No” rather than “No/Yes”) and might click the sad one by mistake if I wasn’t paying attention.

**Comment by mheap** [comment]
We can keep this issue and remove the Volta tag

**Comment by benhayehudi** [comment]
I've gone ahead and reordered the feedback icons to present the "yes" first. I am in agreement that a user might default to the "sad" one because of the order it is currently. This is in PR #1340.
