### ISSUE TITLE
Community Page Renders Unresolved Merge

### ISSUE THREAD

**Issue by cr0wst** [Nexmo/nexmo-developer#997]
## Description

There appears to be an unresolved diff on https://nexmo-developer-staging-pr-825.herokuapp.com/community

## What did you expect to happen?

I expected the community page to render the upcoming events and video links like it does in production.

## What actually happened?

It renders a diff:
```
<<<<<<< HEAD
======= 
>>>>>>> 530e6e4afed026950185e5c9ccbc528c03264502
You can find us at these upcoming events
Subscribe to feed

<<<<<<< HEAD
=======
>>>>>>> 530e6e4afed026950185e5c9ccbc528c03264502
```

## Steps to reproduce:

Navigate to https://nexmo-developer-staging-pr-825.herokuapp.com/community

## Related resources

https://github.com/Nexmo/nexmo-developer/blob/volta/app/views/static/community.html.erb#L8-L74 shows the merge that was never resolved.

**Comment by lornajane** [comment]
Fixed in eff89d5314c2ab13bbe3e65ccb18926a327daf0f
