### ISSUE TITLE
NCCO Ref for Connect examples in different style

### ISSUE THREAD

**Issue by sammachin** [Nexmo/nexmo-developer#998]
https://developer.nexmo.com/voice/voice-api/ncco-reference#connect

## Description

The NCCO reference for the `connect` action is different to the others, the example JSON is after the details (I thought it wasn't there) and you have to scroll through LOTS of different examples, perhaps a tabbed view of the 3 different endpoint types like `conversation` above?

## What did you expect to happen?

The examples to be in the same position and style as the other actions

**Comment by michizhou** [comment]
@sammachin I would be glad to take this issue!

**Comment by mheap** [comment]
@michizhou If you could, that would be great!

**Comment by michizhou** [comment]
@mheap I just wanted to let you know that I recently opened a PR that should resolve this issue. Please let me know if you need me to make any more changes. Thanks!
